### ISSUE TITLE
[BUG] URGENT "No compatible .NET runtime found. Minimum required version is 8.0"

### ISSUE THREAD

**Issue by akoolud** [microsoft/vscode-dotnettools#1005]
### Describe the Issue

I`m getting an error.
maybe extension updated itself without permission.
Its been days and still no fix...

FIX: Downgrade from vscode website to lowest possible version.
I blocked all vscode IPs hopefully they cant break my stuff and ruin my work anymore.

### Expected Behavior

not throwing irrelavent errors for no reason

**Comment by webreidi** [comment]
@akoolud Can you please provide more details on the specific error you are receiving and provide the output for "Projects" from the output pane (Command Palette > .NET: Open Project System Logs)?

**Comment by akoolud** [comment]
its in the title "No compatible .NET runtime found. Minimum required version is 8.0".
it happend right after a restart and without me ever clicking on "Update". broke everything and wasnt showing the debug window. 

after i blocking ips theres no auto update without consent but I see vscode trying to access and keeps spamming requests and still havent found to turn it off. any ideas ? anything that had an option is off

**Comment by nagilson** [comment]
cc @tmeschter @lifengl for this runtime cannot be found issue.

**Comment by Michael-Eng** [comment]
We need more information in order to diagnose this issue. What version of .NET SDK do you have installed? What version the C# Dev Kit was working, and what version stopped working?

@webreidi the .NET7 servicing lifetime ends on May 14, 2024 so the version of C# and C# Dev Kit were intentionally moved to .NET 8

CC @nagilson, @lifengl

**Comment by lifengl** [comment]
@akoolud : because you intentionally block the extension to download necessary NET 8 runtime, you must install NET 8 SDK on your machine to use the extension.

**Comment by EricCarrGH** [comment]
This bit me too - planned to work on stuff on the plane, and suddenly nothing works. 

In the future can you please have it check first if new runtime (e.g. NET 9) exists prior to updating, and display a prompt that requires action, rather than silently update to a version that is broken due to a missing dependency?

I would rather work on an unsupported, working, version for a few days than have nothing work at all.

**Comment by nagilson** [comment]
> This bit me too - planned to work on stuff on the plane, and suddenly nothing works.
> 
> In the future can you please have it check first if new runtime (e.g. NET 9) exists prior to updating, and display a prompt that requires action, rather than silently update to a version that is broken due to a missing dependency?
> 
> I would rather work on an unsupported, working, version for a few days than have nothing work at all.

@EricCarrGH 
This is good feedback. @AArnott @dibarbet To consider to not switch to the new .NET runtime download until we can confirm it has succeeded. given we have successfully installed a .NET Runtime in the past. Our downloading API does return the path which that/erroring out should indicate whether the API succeeded or not.

The main point against doing this is potential security ramifications, if it continues to fail eventually the user would be on an insecure runtime but I dont think we would be super concerned about the exploitability of this.

**Comment by AArnott** [comment]
Our extension requests the .NET 8 runtime because it requires it. Running on .NET 7 temporarily is not an option.
If you don't have .NET 8 downloaded/installed already as the extension requires, yet the extension was working before, the extension must have been updated but not yet run for the first time. There's nothing we can do to improve that short of including the .NET 8 runtime in the extension itself, which I don't see us moving to.

The best advice I can give is avoid setting the extension to auto-update, and only update it when you're about to use it, so that you are guaranteed to have an Internet connection over which to download any runtime dependencies it has.

**Comment by nagilson** [comment]
Due to the way the logic works, this is not just true for going from 8 to 9 but from 8.0.X to 8.0.Z. So I think this is technically the same problem we are discussing in https://github.com/microsoft/vscode-dotnettools/issues/1028

**Comment by EricCarrGH** [comment]
Having authored a vscode extension myself that also installs dependencies *after installation*, I can appreciate that moving dependency installation earlier in the process complicates things.

Perhaps in the future VSCode could have a "Install/verify dependencies" step during Extension installation/update, so a standard is available to address these partial install scenarios, benefiting all extension developers.
