### ISSUE TITLE
BUG Not possible to run and debug "net8.0-macos" projects

### ISSUE THREAD

**Issue by JeroenBer** [microsoft/vscode-dotnettools#1017]
### Describe the Issue

We ported our Xamarin macOS applications to .NET 8 (runtime "net8.0-macos"). Since VS for Mac is End of Life we are using the ".NET MAUI extension for VS Code" in VSCode as a substitute.

Using the curly braces in the bottom it's possible to select an iOS startup project for debugging. However it's NOT possible to select a "net8.0-macos" project for debugging. 

This means it's almost impossible to maintain or develop on this code now that VS for Mac is no longer supported.

### Expected Behavior

Using the ".NET MAUI extension for VS Code" it should be possible to debug "net8.0-macos" projects

### Environment Information

- VS Code Version 1.87.2
- MAUI Extension version v0.9.7

**Comment by mauroa** [comment]
Hi, thanks for the feedback and patience.
macos projects are not supported in .NET MAUI, so we recommend moving to convert your project to target maccatalyst instead.

**Comment by JeroenBer** [comment]
I do not agree, it might not be supported in MAUI but "net8.0-macos" is supported in .NET8 as far as I know. 

Since VS Mac is now end of life it would be necessary to have a way of debugging these projects to be able to maintain them.

Moving to maccatalyst is easier said then done, it's not so easy to just port a large macOS application to maccatalyst, if even possible at all.

**Comment by cabal95** [comment]
I would second that this is not a MAUI issue but a plain dotnet C# issue. I believe this was tagged as MAUI incorrectly, possibly because the OP mentioned ".NET MAUI extension for VS Code". But I have the same issue when MAUI is not involved at all.

Simply run `dotnet new macos`, then open the folder in VS Code. There is no way to run. When you try to run the project via the standard C# extension, it says "the project does not support debugging".

This is clearly possible as the launch file posted above does work and allows debugging without issues. But it took a bunch of Googling to find this thread and understand that the C# extension simply doesn't support running on Mac. At the very least, the error message should be updated to elaborate such as "the C# extension does not support debugging on Mac".
