### ISSUE TITLE
Debugger requres multiple steps

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1025]
Type: <b>Bug</b>

When stepping through Maui code in the debugger, it is often necessary to hit step over/step into five or six times to get it to advance to the next line.

The only real pattern I've seen is that it seems to be async calls.

Extension version: 0.9.7
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.2.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|96.00GB (2.64GB free)|
|Process Argv|--crash-reporter-id 1618046c-b005-4c1a-89ae-cb627902572c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30998029
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:30979542
8082a590:30971561
fegfb526:30981948
bg6jg535:30979843
ccp1r6:30993540
dsvsc020:30976470
pythonaic:30996667
7ghi1836:30988842
dsvsc021:30996838

```

</details>

**Comment by mauroa** [comment]
Hi @mmiller-d8.
With the latest pre-release of MAUI DevKit, we introduced important changes around the debugging experience, so MAUI projects now use the .NET Core Debugger backend to debug the apps, which has multiple advantages, supports more debugging functionality and inherits most of the C# debugger settings.
In order to get this feature enabled, you should update to the latest pre-release of C# and MAUI extensions, and also ensure you have dotnet SDK 8.0.200 or higher.
You should see your issue solved with it, so I'm marking this as fixed.
In case you do the updates and still see this problem, feel free to reopen the ticket and attach the content of the .NET MAUI output pane and the debug console.
Thanks
