### ISSUE TITLE
[FEEDBACK] The experience is nowhere near VS for Mac or Rider

### ISSUE THREAD

**Issue by iam3yal** [microsoft/vscode-dotnettools#1053]
### Feedback

The **C# Dev Kit** experience falls far short of **VS for Mac** and isn't even remotely comparable to **Rider**. If there's a serious intention to transition people from **VS for Mac** to **VSCode** (or from **Rider** for subscribers like myself), then a more serious approach to migration is necessary.

Consider the following points:

- When opening a solution, it should seamlessly navigate to **Solution Explorer** rather than displaying both **Folder Explorer** and **Solution Explorer** simultaneously.
- Keybindings should mirror those of **VS for Mac** (with optional keymaps for **Rider/R#** users).
- Running and debugging should function smoothly without needing to modify launch.json files or mess with configuration at all.
- It should effortlessly support **Blazor**, **MAUI**, and other project types without requiring additional extensions beyond the **C# Dev Kit**. It should encompass all C# project types out of the box, akin to a conventional IDE.

This assessment is based on personal experience, but it feels as though there's an unnecessary level of complexity involved in transitioning from **VS for Mac** or **Rider** to **VSCode**. Respectfully, it doesn't quite embody the essence of an IDE but rather feels more like a side project from a third-party vendor. This observation comes from someone who regularly uses **VSCode** alongside **Rider**, and I can only speculate on the experience for those who are new to it. Therefore, I genuinely hope that with time, improvements will be made to elevate its quality and usability.🤞 

### Environment Information

- OS: macOS 14.4.1 (23E224)
- VSCode: 1.88.0
- C#: 2.24.17 (pre-release)
- C# Dev Kit: 1.5.12 (pre-release)
- .NET MAUI: 0.10.59 (pre-release)
- .NET Install Tool: 2.0.3

**Comment by timheuer** [comment]
Thanks for taking the time to post the feedback @iam3yal!

> * When opening a solution, it should seamlessly navigate to **Solution Explorer** rather than displaying both **Folder Explorer** and **Solution Explorer** simultaneously.

We've heard both mixed feedback here. We are looking to experiment with a setting that does just what you are stating here. The default explorer of course shows your entire workspace and is super valuable so we don't want to relegate that as we have heard that most rely on that 'whole workspace' view quite a bit.

> * Keybindings should mirror those of **VS for Mac** (with optional keymaps for **Rider/R#** users).

Have you manually set your key bindings to match your desires? Are you looking for us to provide a default optional mapping here? If you had to prioritize, what are the most used keybindings you re-map?

> * Running and debugging should function smoothly without needing to modify launch.json files or mess with configuration at all.

The run/debug experience in VSCode is indeed different. In the C# Dev Kit we've tried to do what you mention. You don't need a `launch.json` to run/debug a .NET app within the Dev Kit as we've enabled a dynamic debugger that you can leverage. The way that VS Code works today you do have to choose it once to make it known that's preferred, but you don't have to create a new file though.

> * It should effortlessly support Blazor, MAUI, and other project types without requiring additional extensions beyond the C# Dev Kit. It should encompass all C# project types out of the box, akin to a conventional IDE.

Good to hear this. In your list, MAUI is the only thing that is separate as of now. We've also heard much the opposite of what you're proposing that folks want light-weight fast installs and if they don't use a specific framework, they don't want to have to worry about it (e.g., if you aren't a client developer we've heard feedback they don't want MAUI by default).  

I think your sentiments are reflected in some other issues, but I might encourage you to close this one, and search for others to upvote and/or create individual items here so that we can reason with them and the community separately.  Sound fair? It's better, for example, to have an issue about bringing MAUI in to the extension in one issue that can be discussed, etc. rather than a mutli-topic issue like this, if that makes sense.

**Comment by iam3yal** [comment]
@timheuer I understand. I'll close this and if I wouldn't find an issue about one of the issues mentioned I'll create a new one, thank you! keep up the good work!
