### ISSUE TITLE
C# Dev Kit can't be activated on FreeBSD 13.2 and 12.4 with XFCE4

### ISSUE THREAD

**Issue by HANBAUD** [microsoft/vscode-dotnettools#1055]
Type: <b>Bug</b>

C# Dev Kit extension can't be activated on FreeBSD+XFce4, the RUNNING STATUS of this extension display "Not yet activated."
But the same extension runs well on Ubuntu+XFCE4.
Why?
Thanks.

Extension version: 1.4.29
VS Code version: Code - OSS 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2024-02-20T23:44:23.862Z)
OS version: FreeBSD x64 13.2-RELEASE
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|31.57GB (26.48GB free)|
|Process Argv|--ms-enable-electron-run-as-node --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details>

**Comment by arkalyanms** [comment]
@AArnott would you take a look to see if this is a supported OS combo?

**Comment by sjsepan3** [comment]
# C# Dev Kit can't be activated on GhostBSD 24.01.1 (FreeBSD 14.0-STABLE)

In case this is useful, I would like to add that on GhostBSD (based on FreeBSD)  has same Runtime Status=Not yet activated

## extension

Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 1.7.27
Publisher: ms-dotnettools

## OS

ghostbsd-version:
24.04.1

freebsd-version:
14.0-STABLE

## Code:

VS Code: Code-OSS
Version: 1.88.1
Commit: e170252f762678dec6ca2cc69aba1570769a5d39
Date: 2024-05-07T13:49:21.988Z
Electron: 28.3.1
ElectronBuildId: undefined
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: FreeBSD x64 14.0-STABLE

## System Info

uname -a
FreeBSD *** 14.0-STABLE FreeBSD 14.0-STABLE GENERIC amd64

pkg info | grep "os-generic"
os-generic-kernel-24.04.1,1    FreeBSD kernel without debug enabled
os-generic-userland-24.04.1    Metaport for the FreeBSD userland
os-generic-userland-base-24.04.1 FreeBSD base system share and libexec dirs
os-generic-userland-base-bootstrap-24.04.1 FreeBSD userland libelf, rtld and other critical early libraries
os-generic-userland-bin-24.04.1 FreeBSD userland bin directories and binaries
os-generic-userland-boot-24.04.1 FreeBSD Userland boot directories and files
os-generic-userland-conf-24.04.1 FreeBSD userland etc files and directories
os-generic-userland-devtools-24.04.1 FreeBSD userland compilers and libraries
os-generic-userland-docs-24.04.1 FreeBSD userland documentation and man pages
os-generic-userland-lib-24.04.1 FreeBSD userland lib directories and files
os-generic-userland-lib32-24.04.1 FreeBSD userland 32bit libraries
os-generic-userland-rescue-24.04.1 FreeBSD userland rescue directory and binaries
os-generic-userland-sbin-24.04.1 FreeBSD userland bin directories and binaries


sysinfo: 
*** is redacted info
apologies for the remaining formatting...

Generated by SysInfo v1.0.1 by Daniel Gerzo

-System information-:

Graphic card information:-:
vgapci0@pci0:1:0:0: class=0x030000 rev=0x00 hdr=0x00 vendor=0x1002 device=0x6611 subvendor=0x1028 subdevice=0x2121
vgapci0@pci0:1:0:0: class=0x030000 rev=0x00 hdr=0x00 vendor=0x1002 device=0x6611 subvendor=0x1028 subdevice=0x2121
vendor='Advanced Micro Devices, Inc. [AMD/ATI]'
device='Oland [Radeon HD 8570 / R5 430 OEM / R7 240/340 / Radeon 520 OEM]'
INFO: :Check pciconf(8) for more information.::
-
PCI devices with no driver attached:-:
none0@pci0:0:22:0:	class=0x078000 rev=0x04 hdr=0x00 vendor=0x8086 device=0x8c3a subvendor=0x1028 subdevice=0x05a5
none1@pci0:1:0:1:	class=0x040300 rev=0x00 hdr=0x00 vendor=0x1002 device=0xaab0 subvendor=0x1028 subdevice=0xaab0

-BIOS information-:

WARNING: :You will need to install the sysutils/dmidecode port in order to obtain this information.::

-CPU information-:

Machine class:	amd64
CPU Model:	Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
No. of Cores:	4
Cores per CPU:	
-
CPU usage statistics:-:
CPU:  2.4% user,  0.0% nice,  2.1% system,  0.0% interrupt, 95.4% idle
CPU:  0.2% user,  0.0% nice,  0.2% system,  0.0% interrupt, 99.6% idle

-RAM information-:

-Memory information from dmidecode(8)-:
WARNING: :You will need to install the sysutils/dmidecode port in order to obtain this information.
::
-System memory summary-:
Total real memory available:	11153 MB
Logically used memory:		1521 MB
Logically available memory:	9632 MB

-Swap information-:
Device              Size     Used    Avail Capacity
/dev/label/swap0     2.5G       0B     2.5G     0%

-Operating system information-:

Operating system release:	FreeBSD 14.0-STABLE
OS architecture:		amd64
Hostname:			***
Kernel build dir location:	
Currently booted kernel:	/boot/kernel/kernel

Currently loaded kernel modules (kldstat(8)):
geom_eli.ko
zfs.ko
linprocfs.ko
linux_common.ko
linsysfs.ko
fdescfs.ko
linux.ko
linux64.ko
cuse.ko
fusefs.ko
amdgpu.ko
drm.ko
iic.ko
linuxkpi_video.ko
dmabuf.ko
lindebugfs.ko
ttm.ko
amdgpu_oland_mc_bin.ko
amdgpu_oland_pfp_bin.ko
amdgpu_oland_me_bin.ko
amdgpu_oland_ce_bin.ko
amdgpu_oland_rlc_bin.ko
amdgpu_oland_smc_bin.ko
amdgpu_oland_uvd_bin.ko
vboxdrv.ko
pty.ko
acpi_wmi.ko
ichsmb.ko
smbus.ko
vboxnetflt.ko
netgraph.ko
ng_ether.ko
vboxnetadp.ko
geom_uzip.ko
ums.ko
usbhid.ko
hidbus.ko
ipfw.ko
mac_ntpd.ko
WARNING: :The linprocfs.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The linux_common.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The linsysfs.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The fdescfs.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The linux.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The linux64.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The cuse.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The fusefs.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The drm.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The iic.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The linuxkpi_video.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The dmabuf.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The lindebugfs.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The ttm.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_mc_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_pfp_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_me_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_ce_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_rlc_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_smc_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The amdgpu_oland_uvd_bin.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The vboxdrv.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The pty.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The acpi_wmi.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The ichsmb.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The smbus.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The vboxnetflt.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The netgraph.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The ng_ether.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The vboxnetadp.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The geom_uzip.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The ums.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The usbhid.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The hidbus.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The ipfw.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::
WARNING: :The mac_ntpd.ko module is loaded, however it is not being loaded upon the system boot time from /boot/loader.conf.::

INFO: :For security recommendations see the security(7) man page.::
INFO: :For system tuning advice, see the tuning(7) man page.::
INFO: :To view various system statistics use the systat(1) tool.::
-
Bootloader settings-:
The /boot/loader.conf has the following contents:
rc_system="bsdrc"
crypto_load="YES"
aesni_load="YES"
geom_eli_load="YES"
vfs.zfs.arc_max="512M"
zfs_load="YES"
INFO: :See the loader.conf(5) manual page for more information.::

-System uptime:-:
System is up since Tue Jun 18 14:59:37 2024
 3:02PM  up 2 mins, 3 users, load averages: 0.25, 0.18, 0.08
-
Process statistics:-:
110 processes: 1 running, 109 sleeping

-Jail related information:-:
   JID  IP Address      Hostname                      Path

-Storage information-:

-Available hard drives:-:
ada1: <Samsung SSD 840 EVO 120GB EXT0BB6Q> ACS-2 ATA SATA 3.x device
ada1: Serial Number S1R3NSAF929230T
ada1: 600.000MB/s transfers (SATA 3.x, UDMA6, PIO 512bytes)
ada1: Command Queueing enabled
ada1: 114473MB (234441648 512 byte sectors)
ada1: quirks=0x3<4K,NCQ_TRIM_BROKEN>
cd0: <MATSHITA DVD+-RW SW830 D.03> Removable CD-ROM SCSI device
cd0: Serial Number CN0X85FC3686
cd0: 150.000MB/s transfers (SATA 1.x, UDMA5, ATAPI 12bytes, PIO 8192bytes)
ada0: <ST1000DM003-1SB102 HPH3> ACS-3 ATA SATA 3.x device
ada0: Serial Number W9A299GD
ada0: 600.000MB/s transfers (SATA 3.x, UDMA5, PIO 8192bytes)
ada0: Command Queueing enabled
ada0: 953869MB (1953525168 512 byte sectors)
ada0: quirks=0x1<4K>

-Raid controllers:-:
-ahcich1::
-ahcich2::
-ahcich0::
-
Currently mounted filesystems:-:
zroot/ROOT/default on /
devfs on /dev
procfs on /proc
linprocfs on /compat/linux/proc
tmpfs on /tmp
linsysfs on /compat/linux/sys
fdescfs on /dev/fd
zroot/tmp on /tmp
zroot/usr/home on /usr/home
zroot/var/audit on /var/audit
zroot/usr/src on /usr/src
zroot/var/crash on /var/crash
zroot/var/mail on /var/mail
zroot/usr/ports on /usr/ports
zroot/var/tmp on /var/tmp
devfs on /compat/linux/dev
fdescfs on /compat/linux/dev/fd
tmpfs on /compat/linux/dev/shm
lklfuse on /media/ada0s1

WARNING: :Not found in fstab(5): zroot/ROOT/default on /::
WARNING: :Not found in fstab(5): zroot/tmp on /tmp::
WARNING: :Not found in fstab(5): zroot/usr/home on /usr/home::
WARNING: :Not found in fstab(5): zroot/var/audit on /var/audit::
WARNING: :Not found in fstab(5): zroot/usr/src on /usr/src::
WARNING: :Not found in fstab(5): zroot/var/crash on /var/crash::
WARNING: :Not found in fstab(5): zroot/var/mail on /var/mail::
WARNING: :Not found in fstab(5): zroot/usr/ports on /usr/ports::
WARNING: :Not found in fstab(5): zroot/var/tmp on /var/tmp::
WARNING: :Not found in fstab(5): fdescfs on /compat/linux/dev/fd::
WARNING: :Not found in fstab(5): tmpfs on /compat/linux/dev/shm::
WARNING: :Not found in fstab(5): lklfuse on /media/ada0s1::

-
I/O statistics:-:
       tty             ada0             ada1              cd0             cpu
 tin  tout KB/t   tps  MB/s KB/t   tps  MB/s KB/t   tps  MB/s  us ni sy in id
   0   128 21.0     3  0.07 21.2   103  2.13  0.0     0  0.00   2  0  2  0 95
INFO: :Run iostat(8) or gstat(8) to see live statistics.::
-
Disk usage:-:
Filesystem            Size    Used   Avail Capacity  Mounted on
zroot/ROOT/default     93G     43G     50G    46%    /
devfs                 1.0K      0B    1.0K     0%    /dev
procfs                8.0K      0B    8.0K     0%    /proc
linprocfs             8.0K      0B    8.0K     0%    /compat/linux/proc
tmpfs                  12G    4.0K     12G     0%    /tmp
linsysfs              8.0K      0B    8.0K     0%    /compat/linux/sys
fdescfs               1.0K      0B    1.0K     0%    /dev/fd
zroot/tmp              50G     28M     50G     0%    /tmp
zroot/usr/home         59G    9.6G     50G    16%    /usr/home
zroot/var/audit        50G     96K     50G     0%    /var/audit
zroot/usr/src          50G     96K     50G     0%    /usr/src
zroot/var/crash        50G     96K     50G     0%    /var/crash
zroot/var/mail         50G    132K     50G     0%    /var/mail
zroot/usr/ports        50G     96K     50G     0%    /usr/ports
zroot/var/tmp          50G    100K     50G     0%    /var/tmp
devfs                 1.0K      0B    1.0K     0%    /compat/linux/dev
fdescfs               1.0K      0B    1.0K     0%    /compat/linux/dev/fd
tmpfs                  12G    4.0K     12G     0%    /compat/linux/dev/shm
lklfuse               916G    360G    510G    41%    /media/ada0s1
-
Geli information-:

-Network information-:

***

-
Socket statistics:-:
There are currently 20 listening (8 TCP/12 UDP) and 8 established connections.
INFO: :For more information please see sockstat(8) manual.::

-User related information-:

There are 2 local users (uid > 1000) and 37 system users (uid < 1000).

There are 3 local groups (gid > 1000) and 50 system groups (gid < 1000).

-Users in wheel group (allowed to use su(1)):-:
root,root,sjsepan


-Packages information-:

There are 0 packages installed in the system and 0 of them needs updating.
-Note that this number may be inaccurate, as your ports tree may be outdated too.:

INFO: :Run pkg_info(1) to see a full list of installed packages.::
INFO: :Use pkg_version(1) to inspect what packages are outdated.::
INFO: :Use the portsnap(8) or csup(1) tool to update your ports tree.::

WARNING: :You should install the portaudit(1) tool in order to get information about known security vulnerabilities in your packages.::

-Information related to services-:

WARNING: :vboxservice is supposed to be running, but it isn't.::
WARNING: :webcamd is supposed to be running, but it isn't.::
WARNING: :ipfw is supposed to be running, but it isn't.::
WARNING: :moused is supposed to be running, but it isn't.::
-
Running services-:
-:
-avahi_daemon is running as pid 1747.:
-avahi_dnsconfd is running as pid 1762.:
-cron is running as pid 1800.:
-cupsd is running as pid 1756.:
-dbus is running as pid 1680.:
-devd is running as pid 1052.:
-lightdm is running as pid 1825.:
-ntpd is running as pid 1740.:
-sshd is running as pid 1797.:
-syslogd is running as pid 1630.:
-xrdp is running as pid 1664.:
-xrdp_sesman is running as pid 1767.:

-Not running services-:
-:
-Machine Status:
-JID             IP Address      Hostname                      Path:
-------------------------- ------------:
-APM is disabled:
-aria2 is not running.:
-auditd is not running.:
-auditdistd is not running.:
-automountd is not running.:
-autounmountd is not running.:
-blacklistd is not running.:
-bootparamd is not running.:
-bsnmpd is not running.:
-bthidd is not running.:
-calibre is not running.:
-clamav_clamd is not running.:
-clamav_freshclam is not running.:
-clamav_milter is not running.:
-ctld is not running.:
-cups_browsed is not running.:
-ddb is not running.:
-dnctl is not running.:
-ftpd is not running.:
-ftpproxy is not running.:
-gdm is not running.:
-ggated is not running.:
-git_daemon is not running.:
-gpsd is not running.:
-gssd is not running.:
-hastd is not running.:
-hcsecd is not running.:
-hostapd is not running.:
-inetd is not running.:
-iovctl is not running.:
-ipfs is not running.:
-ipfw is enabled:
-ipfw_netflow is not active:
-ipmon is not running.:
-ipnat is not running.:
-ippool is not running.:
-ipropd_master is not running.:
-ipropd_slave is not running.:
-ipsec is not running.:
-iscsictl is not running.:
-iscsid is not running.:
-jackd is not running.:
-kadmind is not running.:
-kdc is not running.:
-keyserv is not running.:
-kfd is not running.:
-kpasswdd is not running.:
-kpropd is not running.:
-local_unbound is not running.:
-lockd is not running.:
-lpd is not running.:
-miniupnpc is not running.:
-mountd is not running.:
-moused is not running.:
-natd is not running.:
-nfscbd is not running.:
-nfsd is not running.:
-nfsuserd is not running.:
-nmbd is not running.:
-nscd is not running.:
-ntpdate is not running.:
-opensm is not running.:
-openssh is not running.:
-pcscd is not running.:
-pflog is not running.:
-powerd is not running.:
-ppp is not running.:
-rarpd is not running.:
-rfcomm_pppd_server is not running.:
-route6d is not running.:
-routed is not running.:
-rpcbind is not running.:
-rtadvd is not running.:
-rtsold is not running.:
-rwhod is not running.:
-saned is not running.:
-sdpd is not running.:
-smbd is not running.:
-sndiod is not running.:
-statd is not running.:
-sysctl is not running.:
-tlsclntd is not running.:
-tlsservd is not running.:
-ubthidhci is not running.:
-uuidd is not running.:
-vboxservice is not running.:
-vboxwatchdog is not running.:
-vboxwebsrv is not running.:
-watchdogd is not running.:
-webcamd is not running.:
-winbindd is not running.:
-ypbind is not running.:
-ypldap is not running.:
-yppasswdd is not running.:
-ypserv is not running.:
-ypset is not running.:
-ypupdated is not running.:
-ypxfrd is not running.:
-zfsd is not running.:

INFO: :Configuration of system-wide services is located in the /etc/ directory.::
INFO: :Configuration of 3rd party services can be found in the /usr/local/etc/ directory.::

-Misc information-:

-Open file statistics (cur/max):-:
1630/356919 files
-
Resource limits:-:
Resource limits (current):
  cputime              infinity secs
  filesize             infinity kB
  datasize             33554432 kB
  stacksize              524288 kB
  coredumpsize                0 kB
  memoryuse            infinity kB
  memorylocked               64 kB
  maxprocesses            14893
  openfiles              321219
  sbsize               infinity bytes
  vmemoryuse           infinity kB
  pseudo-terminals     infinity
  swapuse              infinity kB
  kqueues              infinity
  umtxp                infinity
-
Information related to cron:-:
There are 6 entries in /etc/crontab

-Current time and date:-:
Tue Jun 18 15:02:12 EDT 2024

**Comment by AArnott** [comment]
I'm not aware of any testing or dogfooding we do with BSD-based OS's. We regularly test Mac, Windows, and Linux (ubuntu), and want to regularly test more flavors of linux. This is the first request for BSD support I've heard of. I'm not sure how much effort it would take to test and support that.

**Comment by sjsepan3** [comment]
> I'm not aware of any testing or dogfooding we do with BSD-based OS's. We regularly test Mac, Windows, and Linux (ubuntu), and want to regularly test more flavors of linux. This is the first request for BSD support I've heard of. I'm not sure how much effort it would take to test and support that.

Understandable, and frankly it wouldn't have come up if there weren't .Net and Code-OSS packages appearing in FreeBSD ports.  For me its a 'nice-to-have' as I investigate GhostBSD, but not critical. Maybe just something for future reference. I was honestly surprised to be able to run Code-OSS and .Net 8.0 there.

**Comment by AArnott** [comment]
Thanks. Ya, I think we have to put this squarely in unsupported territory. Sorry.

**Comment by HANBAUD** [comment]
Thanks.On Jun 22, 2024 5:58 AM, Andrew Arnott ***@***.***> wrote:
I'm not aware of any testing or dogfooding we do with BSD-based OS's. We regularly test Mac, Windows, and Linux (ubuntu), and want to regularly test more flavors of linux. This is the first request for BSD support I've heard of. I'm not sure how much effort it would take to test and support that.
