### ISSUE TITLE
[BUG] New nuget commands do not work with private feed and NuGetPackageSourceCredentials_{name}

### ISSUE THREAD

**Issue by Tobias-08** [microsoft/vscode-dotnettools#1129]
### Describe the Issue

`NuGet: Add NuGet Package` does not find any packages if in `nuget.config` a private feed is used and credentials for this feed are provided via `NuGetPackageSourceCredentials_{name}` env var (see [Microsoft Docs](https://learn.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds#credentials-in-environment-variables)).

It finds packages if credentials are provided directly in `nuget.config` via `<packageSourceCredentials>`.

### Steps To Reproduce

1. Configure a private feed as the only feed
2. Provide credentials via `NuGetPackageSourceCredentials_{name}`
3. Try `NuGet: Add NuGet Package`

### Expected Behavior

`NuGet: Add NuGet Package` works with `NuGetPackageSourceCredentials_{name}`.

### Environment Information

- OS: Ubuntu 24.04 (WSL)
- VS Code: 1.89.1

**Comment by jebriede** [comment]
Thanks for reporting this issue, @Tobias-08. There are a few things that could be causing this so in order to help diagnose the problem, we'll need some more info.

The environment variable will need to be available to VS Code in order for it to be used with the `NuGet: Add NuGet Package` command. The first thing we should do is verify that the environment variable is available to VS Code.

Please [open a terminal](https://code.visualstudio.com/docs/terminal/basics) in VS Code and type:
`gci env:NuGetPackageSourceCredentials_*`

Please let us know if you see any environment variable show up. If not, you'll need to set the environment variable in Windows before launching VS Code or run vs code from the same terminal window where you set the environment variable.

If it is showing up, let's verify that the credentials are set up properly by running the following command from a command prompt or powershell prompt (important: please run this from your project's root directory):
`dotnet package search`

If authentication fails for this command, please let us know. As per the [docs](https://learn.microsoft.com/en-us/nuget/consume-packages/consuming-packages-authenticated-feeds#credentials-in-environment-variables), If the environment variable doesn't match NuGet's convention, or the value doesn't meet NuGet's expected pattern, NuGet will silently ignore the environment variable, and continue searching for credentials for the package source elsewhere. Thanks in advance for getting back to us!

**Comment by Tobias-08** [comment]
@jebriede Thanks for your detailed response. I had a casing error in my env var, sorry. After correcting the casing `NuGet: Add NuGet Package` works as expected.
