### ISSUE TITLE
VSCode Build ignore configuration Release

### ISSUE THREAD

**Issue by Mbprogramming** [microsoft/vscode-dotnettools#1199]
Type: <b>Bug</b>

Create a .net maui app, create a run/debug config (launch.json), add "configuration": "Release"

it is ignored and always "Debug"

Extension version: 1.0.6
VS Code version: Code - Insiders 1.91.0-insider (3b80131054ea2b80002bfde213a41293b85e68de, 2024-06-14T05:49:13.212Z)
OS version: Windows_NT x64 10.0.26236
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (11.67GB free)|
|Process Argv|--crash-reporter-id 5cdf2511-2211-43c1-b10f-36a62b33182f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
2i9eh265:30646982
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonidxpt:30768918
pythonnoceb:30776497
asynctok:30898717
dsvsc013:30777762
dsvsc014:30777825
dsvsc015:30821418
pythontestfixt:30866404
pythonregdiag2:30926734
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
jchc7451:31067543
showvideot:31016890
chatpanelt:31014475
da93g388:31013173
a69g1124:31018687
dvdeprecation:31040973
pythonprt:31036556
dwnewjupytercf:31046870
2f103344:31071589
nb_pri_only:31057983
nativerepl2:31071685
refactort:31073763

```

</details>

**Comment by kbsanders** [comment]
My team ran into this issue as well. I started reverting back, version by version and it didn't start working correctly again until version 0.12.17 (pre-release).

**Comment by pkubs-ui** [comment]
Have you allowed configuration names from launch.json?
I missed it since why even have this option. It's under Settings > .NET MAUI

![image](https://github.com/microsoft/vscode-dotnettools/assets/173266190/d2f5b7e2-4c00-4ad3-86b3-f78d9f660fea)

**Comment by mauroa** [comment]
Hi.

C# DevKit introduced a new feature where you can select your solution configuration from the UI instead of having to define it in the launch.json. That's why .NET MAUI disabled the launch.json usage by default @pkubs-ui. We encourage the users to stop using launch.json for this and instead use the UI that is now available in VS Code. 

Please update C#, C# DevKit and .NET MAUI to latest pre-release versions, and you will see the following option in VS Code to select you configurations:

You can click at the bottom left in VS Code:

![SolutionConfigs1](https://github.com/microsoft/vscode-dotnettools/assets/2921919/17dce90c-d48c-462b-a6a0-ad6111da2031)

Or you can show the command palette and select the command below:

![SolutionConfigs2](https://github.com/microsoft/vscode-dotnettools/assets/2921919/47f077b6-0ac3-4a4a-a2f8-f2e1b776bae3)

I'll mark this issue as fixed. Feel free to request a reopening in case this didn't work for you.
Thanks

**Comment by richaplinvs** [comment]
It looks like you still need a launch.json file to make the new VS Code UI work? Without it I don't get the option in the bottom left toolbar.

I assume you mean don't use the launch.json with the older VSCode UI "Run and Debug" section with the play button that's available with the launch.json?
