### ISSUE TITLE
[BUG] "A compatible .NET SDK was not found" when opening workspace

### ISSUE THREAD

**Issue by Geeknerd1337** [microsoft/vscode-dotnettools#120]
### Describe the Issue

I've got the .NET SDK installed and use visual studio just fine, but for some reason when I open a project in VSCode with the C# DevKit installed I get the following error:
![image](https://github.com/microsoft/vscode-dotnettools/assets/15205856/a61e6bcf-c4fb-49fa-be88-39b6cc05bfa2)

### Steps To Reproduce

1. Install the C# Dev Kit
2. Open a folder with a `.csproj` file in it.
3. View error

### Environment Information

- OS: Windows 10 10.0.19044 Build 19044

**Comment by Odyze** [comment]
I have the same Issue, if reinstalled all my SDK's and tried a lot to get it running, I have a second machine where the Extension runs without any problems.

I'm suspecting an Issue with the PATH variable and the fact, that my Profile Folder contains a '_' <space> character...

![image](https://github.com/microsoft/vscode-dotnettools/assets/46613730/5aed58bc-0eb6-4678-b8a4-7717e2bcdd36)

**Comment by pfeurean** [comment]
this is a duplicate of #24

**Comment by starball5** [comment]
Related on Stack Overflow: [C# Dev Kit (VSCode) on MacOS: Compatible .NET SDK was not found](https://stackoverflow.com/q/76476386/11107541)

**Comment by Michael-Eng** [comment]
Closing as a dup of #24

**Comment by Jxwoon** [comment]
There was a pre-release v0.2.70 for C# Dev Kit to fix #24. Please let us know if that works for you. Thanks!

**Comment by humandigital-ruud** [comment]
Unfortunately, the issue still exists for me after updating to v0.2.70.
I don't see any exception message in any of the outputs, only the "A compatible .NET SDK was not found" message in the Solution Explorer and the log message that 1 project failed to load - it does not say why it failed.

Let me know if I can provide any additional details that may help resolve the issue.

![image](https://github.com/microsoft/vscode-dotnettools/assets/119449492/eedf69be-519d-421e-b9f9-ec17d235621c)

**Comment by lifengl** [comment]
There are likely two issues in this thread, one is related to space characters are not quoted when the extension spins off child processes, which leads projects to be failed to be loaded. That issue was tracked with #24, and should have been fixed.

The second issue is related to certain Mac environment, and it is likely a duplicated of #194. Both CsDevKit extension and SDK are built to match physical CPU architecture, which can be X64 for intel CPUs, and ARM64 for Apple M1/M2 chips. The one to be installed should match the physical CPU of the hardware. On the other side, M1/M2 machine has simulation layer to allow intel based application to run.  However, the CSDevKit and SDK must match. It would not work, if the extension is targeting ARM, and the SDK targets intel, because the extension would load msbuild from SDK into the same process, and mixed CPU binaries would not work.

@humandigital-ruud: can you check whether this happens to be the problem you may run into?

**Comment by lifengl** [comment]
actually, the screen-shot tells the SDK is intel based

![image](https://github.com/microsoft/vscode-dotnettools/assets/11638466/7365c7cd-e85a-45e7-ae21-15a541d3f502)

But it cut out the information of the extension. If the extension is ARM based, it will fail to work with the SDK.

**Comment by humandigital-ruud** [comment]
@lifengl How can I check if the extension is ARM based?
I looked through all the different log outputs but couldn't find anything.

**Comment by lifengl** [comment]
Take a look directory name of binaries in the C# Dev Kit (path can be found in CsDevKit extension logs), if it is a ARM based extension, some binaries are in folder name like Darwin.arm64, otherwise, Darwin.X64 or something similar.

**Comment by lifengl** [comment]
@humandigital-ruud : I started to doubt your issue was the same problem. I checked code logic today, and think the wrong CPU structure would cause exception to be thrown earlier, and it may not execute the code to print out the dotnet --info.

I do hear some people ran into problems to resolve SDK on Mac, and the problem went away after rebooting the machine after installing the SDK. Before that, command line like dotnet --info prints out correct SDK information, but MSBuildLocator doesn't resolve it correctly. I am not sure the reason. Give it a try if you installed the SDK recently.

**Comment by humandigital-ruud** [comment]
@lifengl: I tried a reboot but that didn't help.
Also checked the CPU architecture of CSDevKit and found that it's the correct one: `ms-dotnettools.csdevkit-0.2.99-darwin-x64`

**Comment by lifengl** [comment]
@humandigital-ruud : can you help to check vs code extension log files to see whether it prints out any error there.

To get to the log, you can use vscode command: Developers: Open Extensions Logs folder

There, go inside ms-dotnettools.csdevkit\ServiceHub folder

The project system log is mostly inside a file named with pattern like:

**-Microsoft.VisualStudio.ProjectSystem.CompositionService-*****-********-1.log

it will print out how it started BuildHost (which is used to resolve SDK)

06/29/2023 16:58:41 Pacific Standard Time: Information : 21452 :PID=45804 CMD=***/Microsoft.VisualStudio.ProjectSystem.Server.BuildHost.dll

Some text below this line might give some clue. During the initialization, several code paths are running at the same time, so not all messages might be related.

**Comment by DoubleTK** [comment]
I ran into this same issue on my m1 Mac as well. After looking at the logs, I saw the DOTNET_ROOT environment variable was not set. I tried to set it but still received a failure. Running `which dotnet` told me it was using the dotnet SDK that I had installed using homebrew. 

Uninstalling dotnet using `brew uninstall dotnet` and then installing using the `,pkg` file from Microsoft's website fixed the problem for me. 

I'm not sure if it was just a pathing issue that could be fixed by updating DOTNET_ROOT, but this solution fixed it for me.

**Comment by humandigital-ruud** [comment]
I have also uninstalled the homebrew dotnet and then installed using the `pkg` file and that has resolved the issue for me too!

**Comment by lifengl** [comment]
thanks a lot to let us know this problem and solution.  I will talk to developer who know msbuildLocator package/the logic to resolve SDKs to see what leads the problem to work with dotnet installed in this way.

Generally, the logic to resolve SDK is to locate the first dotnet from PATH, and then it assumes some folder structure to look for SDKs under the folder. There could be some gaps between how things are layout on the disk, which leads the logic to fail.

**Comment by islam-kutkeev** [comment]
i had same problem, but i never use homebrew to install .NET SDK
![Screen Shot 2023-07-17 at 09 55 53](https://github.com/microsoft/vscode-dotnettools/assets/139732503/a290477a-6d3a-4e14-bcf3-1a3c0ae9a837)

**Comment by foman** [comment]
I experienced the same issue with version 0.2.100.
![image](https://github.com/microsoft/vscode-dotnettools/assets/505913/34cc1ab6-5a21-4ea7-b0fa-454e1419012b)

**Comment by timjroberts** [comment]
_I have a workaround... and possibly some additional info for someone investigating..._

In my previous post, from the log it is clear that it is failing to resolve the .NET Core SDK, since it cannot locate a `hostfxr` or a `libhostfxr` library:

```
07/17/2023 15:48:47 Greenwich Mean Time: Error : 9543 :!!Resolve NET Core SDK: Failed
System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/hostfxr.dylib, 1): image not found
dlopen(/Users/timjroberts/.vscode/extensions/ms-dotnettools.csdevkit-0.2.100-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/hostfxr.dylib, 1): image not found
dlopen(hostfxr.dylib, 1): image not found
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libhostfxr.dylib, 1): image not found
dlopen(/Users/timjroberts/.vscode/extensions/ms-dotnettools.csdevkit-0.2.100-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/libhostfxr.dylib, 1): image not found
dlopen(libhostfxr.dylib, 1): image not found
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/hostfxr, 1): image not found
dlopen(/Users/timjroberts/.vscode/extensions/ms-dotnettools.csdevkit-0.2.100-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/hostfxr, 1): image not found
dlopen(hostfxr, 1): image not found
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9/libhostfxr, 1): image not found
dlopen(/Users/timjroberts/.vscode/extensions/ms-dotnettools.csdevkit-0.2.100-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/libhostfxr, 1): image not found
dlopen(libhostfxr, 1): image not found
```

The `dlopen` calls are failing to find a `.dylib` at any of those listed folders (on a fresh .pkg install of .NET 7 SDK). However, a `libhostfxr.dylib` file is present in the `/usr/local/share/dotnet/host/fxr/7.0.9` folder.

If I copy that file into one of the listed folders, i.e.,:
`sudo cp /usr/local/share/dotnet/host/fxr/7.0.9/libhostfxr.dylib /usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.9`, then the Solution Explorer now loads the project as expected:

![image](https://github.com/microsoft/vscode-dotnettools/assets/307586/5e2c5bfe-efbb-4fa0-a356-d4739dca2e46)

**Comment by YuliiaKovalova** [comment]
@lifengl  FYI: https://github.com/microsoft/vscode-dotnettools/issues/120#issuecomment-1640892593

**Comment by foman** [comment]
@timjroberts tks, it works for me.

**Comment by grayu** [comment]
@timjroberts tks, it works for me to.

**Comment by YuliiaKovalova** [comment]
Hi @timjroberts,

Thank you for sharing the workaround.
If you have any chance check if after removing the hack and updating cs dev kit version the problem is still relevant.

**Comment by timjroberts** [comment]
@YuliiaKovalova - Sure. Could you just confirm which version you'd like me to test.

**Comment by timjroberts** [comment]
@YuliiaKovalova, if I remove the `'libhostfxr.dylib'` file from the location I copy it to as part of my workaround, then version `0.4.2` of the Dev Kit works as expected.

I now get a working Solution Explorer without having to copy that file.

**Comment by xendren** [comment]
For reference, I installed the pre-release version v0.4.2, and experienced the same problem on M2 MacBook Air.  Following the workaround as stated above by removing any Homebrew installed SDK's and installing from the MS package did resolve the issue.

**Comment by lifengl** [comment]
add a link to the msbuildLocator issue https://github.com/dotnet/msbuild/issues/9038

**Comment by felipe-b-oliveira** [comment]
> I ran into this same issue on my m1 Mac as well. After looking at the logs, I saw the DOTNET_ROOT environment variable was not set. I tried to set it but still received a failure. Running `which dotnet` told me it was using the dotnet SDK that I had installed using homebrew.
> 
> Uninstalling dotnet using `brew uninstall dotnet` and then installing using the `,pkg` file from Microsoft's website fixed the problem for me.
> 
> I'm not sure if it was just a pathing issue that could be fixed by updating DOTNET_ROOT, but this solution fixed it for me.

Installing from Microsoft official repo also worked for me: 
[https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#register-the-microsoft-package-repository](url)

**Comment by YuliiaKovalova** [comment]
The issue was addressed in the scope of https://github.com/dotnet/msbuild/issues/9038

The public package with version [1.5.6](https://www.nuget.org/packages/Microsoft.Build.Locator/1.5.6) contains the fix.
