### ISSUE TITLE
[BUG] Unable to debug on simulators or physical devices after latest update

### ISSUE THREAD

**Issue by BrandanN21** [microsoft/vscode-dotnettools#1252]
### Describe the Issue

After the latest update on June 26th 2024 our team can no longer debug on any iOS simulators or devices. 

With VS for Mac going end of life here shortly it is vital that the MAUI extension is stable!

### Steps To Reproduce

Debug against iOS simulator or Physical device.

### Expected Behavior

We should be able to debug against simulators or physical devices. 

### Environment Information

MacOS.

**Comment by AbhitejJohn** [comment]
Tagging @AllenD-MSFT. This seems blocking.

**Comment by mauroa** [comment]
Hi @BrandanN21.

Could you give us more info about your case? 
Are you getting the app built, deployed and launched but no breakpoints are hit? Are you having errors before the debug session is started?

If you could also please share the content of the .NET MAUI output, debug output and build output, it would be helpful as well to understand what's happening with your environment.

One final question, is this problem reproducible with any MAUI app?

One more thing, please ensure that you also have the latest C# pre-release version installed, since most of the debug engine lives in there and there have been fixes around it that are required by the .NET MAUI extension.

**Comment by BrandanN21** [comment]
@mauroa 

Thanks for the reply, yes we are able to get the app built and deployed to our physical devices and simulators, but it fails to launch and connect debugging on both simulators and physical devices. 

We do not get any errors in terms of bugs, I will grab the output - but it consistently shows an exiting early due to double fault. When we use VS for Mac there are no issues at all. 

I will spin up a MAUI sandbox app to work to reproduce this on a sample app to help eliminate the potential of something else being the issue. 

In my environment I am not using a pre-release version of the c# extension. I will circle back with my team and gather output from them, ensure they are using pre-release version of the c# extension and get back to you. 

Thanks!

**Comment by BrandanN21** [comment]
After digging into this issue more we can reproduce it in other IDE's as well. We were able to narrow down that it is outputting some proxy errors specifically only when debugging the application. We have reached out to the proper channels to see if there was something that has changed in our vpn. 

Closing this issue and will re-open a new one if we still have trouble after we get that resolved.
