### ISSUE TITLE
[BUG] High CPU  800%

### ISSUE THREAD

**Issue by dingxiaolong** [microsoft/vscode-dotnettools#1424]
### Describe the Issue

After run some time ,  the CPU become 800% ?   
I can't believe it,  shit .
![image](https://github.com/user-attachments/assets/3affc784-d743-4f88-b069-68da0177fdaf)

**Comment by arkalyanms** [comment]
Dup of https://github.com/microsoft/vscode-dotnettools/issues/1382https://github.com/microsoft/vscode-dotnettools/issues/1382

**Comment by lifengl** [comment]
the original description was deleted by system due to improper language usages. basic information I remember:

1, it is on Mac
2, the CPU usage is in a single dotnet process.

My impression is that it is more likely the Roslyn process. Project system is hosted in serviceHost process. DT build processes are hosted in dotnet, but it usually appears as multiple ones (as projects were signed to multiple nodes, and CPU in per process is more limited.)
