### ISSUE TITLE
[BUG] Solution explorer steals focus on startup

### ISSUE THREAD

**Issue by ascott18** [microsoft/vscode-dotnettools#1493]
### Describe the Issue

When VS code starts, after this extension loads it force-focuses the "Solution Explorer" section in the "Explorer" pane. This takes focus away from the tasks I was attempting to perform in other panes.

### Steps To Reproduce

1. Open C# project
2. Immediately begin using the search pane to search for something
3. As the search results are loading, the "Solution Explorer" steals focus away from the search pane, forcing me to navigate back to the search pane to view my search results.

### Expected Behavior

Solution explorer never steals focus away from what I'm doing for any reason.

### Environment Information

Win 10, VS Code 1.93.1, Extension 1.10.18

**Comment by ascott18** [comment]
The "auto sync" setting is not enabled 
![image](https://github.com/user-attachments/assets/98a3e1c0-3128-4707-a244-a51032f4d0f3)

**Comment by webreidi** [comment]
@Jxwoon this may be from the experiment you are running. We would want it open by default, but not to take focus. If they are on a different pane, it should stay on that pane, just be open when they go to the Explorer Pane.

**Comment by mjrist** [comment]
I'm experiencing the same thing here as of 1.10.18.

Along with the focus the solution explorer expands open automatically. This is annoying. If I had it collapsed, it should stay collapsed.

Also if you hide it
![image](https://github.com/user-attachments/assets/873b9323-5731-4fac-a47b-fa0fc0d0da71)
it reappears when the window is reloaded.

We generate and load solutions for intellisense to work but we use the file explorer instead of the solution explorer. It is bothersome for us that it keeps expanding/reappearing.

**Comment by Jxwoon** [comment]
Apologies for the inconvenience. A fix has been made internally and will be available in the next pre-release.

**Comment by Jxwoon** [comment]
The fixed was made to version 1.12.2 to prevent the focus from being stolen. Please try it out and let me know if the issue still persists. Thanks!
