### ISSUE TITLE
NuGet management issues

### ISSUE THREAD

**Issue by HobDev** [microsoft/vscode-dotnettools#1629]
Type: <b>Bug</b>

When I try to update NuGet from the .NET Maui project The Dependencies show packages separately for each target platform. The NuGet are installed at project level and does not need to be shown for each platform.
Further when I right click and update the NuGet I don't see any feedback about the status of update and the NuGet versions don't change in the csproj. 
Finally I able to udate the NuGets manually by mapping each NuGet version with the NuGet website.

Extension version: 1.13.9
VS Code version: Code 1.95.3 (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600XT 6-Core Processor             (12 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.49GB free)|
|Process Argv|--crash-reporter-id 7efd9556-740e-43d4-91b8-9e199325f5bc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
nativerepl2:31139839
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1cf:31157160
5fd0e150:31155592
dwcopilot:31170013
stablechunks:31184530

```

</details>

**Comment by HobDev** [comment]
Bug report  #1523 , #1554 and #1629 seems to be the same issue?

**Comment by kartheekp-ms** [comment]
> When I try to update NuGet from the .NET Maui project The Dependencies show packages separately for each target platform. The NuGet are installed at project level and does not need to be shown for each platform.

It is by design that C# Dev Kit extension in VS Code and Visual Studio displays packages for each target framework separately. The reason is that is valid scenario to have different packages for each target framework. Hope this addresses your concerns regarding this comment.

> Further when I right click and update the NuGet I don't see any feedback about the status of update and the NuGet versions don't change in the csproj.

@HobDev  I am unable to reproduce this issue. Here are the steps I followed:

1. Opened a solution in VS Code with a sample class library project.
2. Used the `Add New Project` feature to add a MAUI app to the solution.
3. Changed the package version of the `Microsoft.Extensions.Logging.Debug` package in the MAUI app project file to 8.0.1.
4. Navigated to the "NuGet: Update package" feature in the command palette.
5. Updated the package version of the `Microsoft.Extensions.Logging.Debug` package to 9.0.0.

I noticed that the new package version is reflected in both the `.csproj` file and the solution explorer.

Please provide additional information about the restore or update package failure, which can be obtained from the `View > Output > NuGet` window. It would also be very helpful if you could upload a sample solution for us to reproduce the issue.

**Comment by HobDev** [comment]
I no longer see the bug. It could be due to some mistakes in upgrading my .net 8 project to .net 9.
