### ISSUE TITLE
[BUG] Output window is opened automatically every time VS Code starts

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#192]
### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/5844

## Steps to reproduce

1. Open VS Code for a folder with a C# solution or project
2. The output window automatically opens with a message `Starting command: "dotnet.exe" restore`

## Expected  behavior
I would expect the C# extension to just work in the background.  It's annoying that I have to close the output pane every single time VS Code opens with a C# project to tell me it's installing packages.  I don't really need to know this, at best it should be configurable.

## Actual behavior

Every time VS Code opens the output window pops up to tell me NuGet is restoring packages

### Environment Information

VS Code version:
C# Extension version: 2.0.212

**Comment by prashantvc** [comment]
Ugh, hope it get fixed soon. It's driving me crazy when I am debugging an extension

**Comment by kartheekp-ms** [comment]
When a solution is opened in the C# Dev Kit extension, the NuGet output window will be automatically opened to display restore logs. The primary reason is to facilitate authentication with any private NuGet Azure DevOps feed that may be configured. The device login details are displayed in the NuGet output window, and users are required to click and input a code for authentication within a 90-second window. If we don't auto-display this output window, users might miss this step and encounter restore failures, often signaled by 401 errors.

Automatically opening the output window may not be a good user experience for customers who use public feeds to restore packages because there won't be any authentication involved. NuGet brokered service displays a warning message when restore fails, providing an option for users to look at the restore failure logs.

This issue has been fixed internally and I hope it will be part of July 2023 release. With this change, NuGet output window will be automatically opened only when workspace setting `autoOpenOutputWindowOnRestore` is set to `on`. This setting is, by default, set to `off`. Customers have the option to change this setting on a workspace basis to enable the automatic opening of the output window.

**Comment by webreidi** [comment]
This was addressed in the latest version of C# Dev Kit (0.3.21+). Please reopen the ticket if you are still experiencing problems.
