### ISSUE TITLE
Enabling solution wide analysis attempts to compute diagnostics for non-source files

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#209]
From vscode-csharp created by [mavasani](https://github.com/mavasani): dotnet/vscode-csharp#5872  

https://github.com/dotnet/vscode-csharp/pull/5868 enables solution wide analysis. Once enabled, we seem to be attempting to calculate diagnostics in non-source files: see nodes for `exec` and `csc.dll` below

![image](https://github.com/dotnet/vscode-csharp/assets/10605811/88176780-1749-4bea-b72a-d56ed5b6b6d5)

**Repro project:** [TestEFApp.zip](https://github.com/dotnet/vscode-csharp/files/11890539/TestEFApp.zip)

Looking under the debugger, it seems we might be adding invalid documents to the project:

![image](https://github.com/dotnet/vscode-csharp/assets/10605811/0a66dab2-08fb-4589-948f-3a727f523324)

**Comment by tmeschter** [comment]
In the context of a design-time build, the output of the `CoreCompile` target is a set of MSBuild items where each item represents an argument to the compiler process. The Project System runs these through the C# compiler command line parser to classify them (source file, metadata reference, analyzer reference, command line switch, etc.) and extract the core information from each one (such as the file path or switch value). This is the information that is then passed to the Language Service.

I suspect what is happening is that the "real" build would have run `dotnet.exe exec csc.dll Foo.cs` and so we see "exec", "csc.dll", and "Foo.cs" as separate MSBuild items representing the arguments. The command line argument parser then decides that these are all source files since the structure doesn't match anything else.

I think the most reliable fix would be to update the CoreCompile target to avoid creating MSBuild items for "exec" and "csc.dll" since those are arguments dotnet.exe rather than the compiler itself. That's an SDK change, though, and doesn't help us with projects using an older SDK (unless we want to service them). A more general fix might be to have the Project System filter out "source" files that don't end in .cs. Do you see any downside to that?

**Comment by dibarbet** [comment]
I'll tag in @jasonmalinowski to comment as well, but having the project system filter out files without .cs does seem reasonable.  Although do we need to consider csx files as well?

**Comment by smitpatel** [comment]
Are there form other than `dotnet.exe exec csc.dll ....`? May be we can exclude additional args being passed to dotnet if that set is defined by us.

**Comment by tmeschter** [comment]
@smitpatel If we're not using the .NET Core version of the compiler, we may have `csc.exe Foo.cs` instead of `dotnet exec csc.dell Foo.cs`. In that case all the arguments really are arguments to the compiler.

**Comment by tmeschter** [comment]
@dibarbet Are there any situations where we would pass a .csx to the compiler as though it were a .cs file?

**Comment by jasonmalinowski** [comment]
The exec item is fallout from https://github.com/dotnet/roslyn/issues/67102, since the project system is expecting (reasonably, in my opinion) that the Csc arguments are indeed just the arguments to Csc, and not the implicit dotnet exec. I consider this a compiler bug, but as @tmeschter observes if we have to deal with existing SDKs, the workaround @jaredpar suggested there is to just recognize if the first arguments are "exec" and DLL path, just skip those two arguments and look at the rest. I'd recommend doing that skipping _before_ passing anything into any further C# command line parsing logic, since they are indeed not C# command line flags.

> @dibarbet Are there any situations where we would pass a .csx to the compiler as though it were a .cs file?

At one point we were looking at supporting .csx files as inputs into projects; I'm not sure if we ever completed that or not. @tmat would know, but I'd expect any workaround here to not be sniffing file extensions to include/exclude source files in the first place, so the question would be somewhat moot.

**Comment by tmat** [comment]
>I'd expect any workaround here to not be sniffing file extensions to include/exclude source files in the first place, so the question would be somewhat moot.

+1

**Comment by tmat** [comment]
I can have a valid C# file called "exec", btw.

**Comment by jasonmalinowski** [comment]
Yeah, I'm sure we have customers out there who have non-conventionally-named C# source files.

**Comment by tmeschter** [comment]
OK, then I propose the project system do the following:

- if the first argument is "exec" **and** the second argument ends with the file name and extension "csc.dll" **then** they will both be ignored

Does that sound reasonable?

**Comment by tmat** [comment]
I believe the compiler should be changed to not include "exec" and "csc.dll" in the item group. See https://github.com/dotnet/roslyn/issues/67102#issuecomment-1624166288

**Comment by tmeschter** [comment]
@tmat I agree. However, there are two issues with that:

1. Other tools have taken a dependency on the current behavior and we risk breaking them. That argument doesn't carry much weight with me personally, but there it is.
2. Whatever change we made on the compiler side (really the C#/VB tasks and targets in MSBuild) would only be available in newer versions of the SDK (and older ones if we serviced them). We would still need a workaround in the project system or language service for SDKs without the fix.

So I'm all for fixing the compiler side, and I'll even do the work if we can get all the stakeholders to agree to it. Until then I'll do what I can in the project system.

**Comment by tmat** [comment]
> [1] Other tools have taken a dependency on the current behavior and we risk breaking them. That argument doesn't carry much weight with me personally, but there it is.

I have not seen evidence of that.

> We would still need a workaround in the project system or language service for SDKs without the fix.

Yes, a workaround suggested above https://github.com/microsoft/vscode-dotnettools/issues/209#issuecomment-1623944185 is reasonable to handle older SDKs.

**Comment by jasonmalinowski** [comment]
> I have not seen evidence of that.

I haven't seen evidence of this either -- I've continued to see more tools working around it! That all said, yes, broken SDKs have shipped, so that ship has already sailed (and is leaking, but alas...)

**Comment by jaredpar** [comment]
I think the workaround for checking for `"exec"` in older SDKs is reasonable. It will break precisely zero people. If that number turns out to be non-zero there are options for the developer to unblock themselves.

**Comment by tmeschter** [comment]
Fixed in version 0.3.2.
