### ISSUE TITLE
[BUG] Extension stops working after restarting Vscode

### ISSUE THREAD

**Issue by phildaniels** [microsoft/vscode-dotnettools#238]
### Describe the Issue

When using the extension, after a while, (normally after restarting vscode), intellisense stops working and I get bizarre compiler errors like "Predefined type 'System.String' is not defined or importedRoslyn[CS0518]". The only way to fix is to fully uninstall the extension, close vscode, and delete  "~/.vscode-server/data/User/globalStorage/ms-dotnettools.csdevkit" and "ms-dotnettools.vscode-dotnet-runtime", then reinstall.

When the error is occuring, the following error appears in the output window under "C#":

```
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
[Error - 2:01:26 PM] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

### Steps To Reproduce

1. Use C# Dev Kit (and related extensions), working on a solution in wsl
2. Close the extension
3. Reopen the extension

### Expected Behavior

The intellisense, and errors in the extension should work

### Environment Information

WSL Version:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

VsCode Version: 
Version: 1.80.0 (user setup)
Commit: 660393deaaa6d1996740ff4880f1bad43768c814
Date: 2023-07-04T15:06:02.407Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Extension versions:
.NET Install Tool for Extension Authors -
v1.6.0
C# -
v2.0.248
C# Dev Kit
v0.1.103

**Comment by arkalyanms** [comment]
The error indicates C# Dev Kit was not available over the bridge. The user's workaround also reflects the same where reinstalling C# Dev Kit fixes the issue.

**Comment by AArnott** [comment]
@dibarbet This describes it working at first, and dying mid-session. Why would a bridge be created in the middle of a working session?

**Comment by arkalyanms** [comment]
Would a LS restart (option changes / dependent extension updates) reestablish the bridge?

**Comment by dibarbet** [comment]
Yeah - an LS restart will cause the bridge to be re-established because the process restarts.  The LS can currently restart for the following reasons:
1.  The server encounters an unrecoverable error in handling certain state-modifying LSP requests.  This is unexpected and generally indicates a bug.
2.  The client encounters an unrecoverable error in handling LSP responses (I know of one active bug here due to serialization).
3.  The restart language server command
4.  On option changes we prompt to restart the language server

While the bridge can generally be re-established, there is currently a bug with devkit where the project information is not sent again after a restart, so we lose all project data on the roslyn server side - see https://github.com/dotnet/vscode-csharp/issues/5882 .  I'm currently applying a workaround to 4) so that we reload the window instead to avoid people accidentally falling into this trap.

*However* - I'm not entirely clear if that is what is happening in this issue.  The repro steps say
> Use C# Dev Kit (and related extensions), working on a solution in wsl
Close the extension
Reopen the extension

@phildaniels can you clarify what you mean by closing / reopening the extension?  Is that a reload of the window, closing and re-opening vscode, or something else?

Additionally - if you wouldn't mind setting `dotnet.server.trace` configuration to `Trace`, re-running the repro and then attaching the entire contents of the extensions log folder:
<img width="488" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5749229/a3bd6879-ffaf-4b2b-a4d5-91c4f3d564e6">

This will include information on the project/sln being loaded, so if it is sensitive feel free to email it to me ([dabarbet@microsoft.com](mailto:dabarbet@microsoft.com)) instead of including on the github issue.

**Comment by phildaniels** [comment]
> @phildaniels can you clarify what you mean by closing / reopening the extension? Is that a reload of the window, closing and re-opening vscode, or something else?

When closing and reopening vscode

> Additionally - if you wouldn't mind setting dotnet.server.trace configuration to Trace, re-running the repro and then attaching the entire contents of the extensions log folder:

Will do, you'll see an email from me shortly

**Comment by solrevdev** [comment]
>Additionally - if you wouldn't mind setting dotnet.server.trace configuration to Trace, re-running the repro and then attaching the entire contents of the extensions log folder:

@dibarbet  You should have received an email from me with this information as well see comment https://github.com/microsoft/vscode-dotnettools/issues/226#issuecomment-1702416050

**Comment by dibarbet** [comment]
Apologies for the late reply here, have had a stack of issues to go through.  I've dug through the logs you both sent (thanks much for those).

There aren't any obvious problems - there is 1 reported error:
```
[Error - 2:01:26 PM] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
   at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
```

but this error shouldn't actually affect functionality and is safe to ignore (we're absolutely fix this so it doesn't show up though).  All the various extension features like sln explorer / intellisense should all continue to work even if you see this pop up in the logs.

We've made a fair number of improvements around dotnet discovery, general server stability, and project loading functionality since this issue has been filed.  Would you mind trying on the latest versions of the C# extension and C# devkit and let me know if you're still having problems?

**Comment by dibarbet** [comment]
Slight add-on here.  There is an issue with project information getting lost when the C# extension restarts - see https://github.com/dotnet/vscode-csharp/issues/5882

The general workaround is to reload the window instead of restarting the server

**Comment by solrevdev** [comment]
> Would you mind trying on the latest versions of the C# extension and C# devkit and let me know if you're still having problems?

Sure, next week I'll switch back to my Visual Studio Code Insiders/C# DevKit setup, rather than continuing with my Visual Studio Code/C# OmniSharp setup.

Thanks for looking into this @dibarbet  and getting back to us. It's much appreciated. 🙏🏼️

**Comment by phildaniels** [comment]
> Apologies for the late reply here, have had a stack of issues to go through. I've dug through the logs you both sent (thanks much for those).
> 
> There aren't any obvious problems - there is 1 reported error:
> 
> ```
> [Error - 2:01:26 PM] [LanguageServerHost]System.InvalidOperationException: Was not able to get hello world response from remote - line 39
>    at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
>    at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.Services.HelloWorld.RemoteHelloWorldProvider.SayHelloToRemoteServerAsync(CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/Services/HelloWorld/RemoteHelloWorldProvider.cs:line 39
>    at Microsoft.CodeAnalysis.LanguageServer.BrokeredServices.ServiceBrokerFactory.CreateAndConnectAsync(String brokeredServicePipeName) in /_/src/Features/LanguageServer/Microsoft.CodeAnalysis.LanguageServer/BrokeredServices/ServiceBrokerFactory.cs:line 82
>    at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
> ```
> 
> but this error shouldn't actually affect functionality and is safe to ignore (we're absolutely fix this so it doesn't show up though). All the various extension features like sln explorer / intellisense should all continue to work even if you see this pop up in the logs.
> 
> We've made a fair number of improvements around dotnet discovery, general server stability, and project loading functionality since this issue has been filed. Would you mind trying on the latest versions of the C# extension and C# devkit and let me know if you're still having problems?

It's working for me now, I can open another issue if I see it again, so thank you for your help on this

**Comment by dibarbet** [comment]
Great to hear!  I'll close this, and yup if you encounter further issues please open a new one.
