### ISSUE TITLE
[BUG]  Unable to apply environment variable settings from launchSettings.json

### ISSUE THREAD

**Issue by philipmat** [microsoft/vscode-dotnettools#241]
### Describe the Issue

When starting (Debug -> Start New Instance) a project from the Solution Explorer, I get the following output:

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
WARNING: Unable to apply environment variable settings from '/Users/philip/Dev/project name>/Properties/launchSettings.json'. Can not add property env to Newtonsoft.Json.Linq.JObject. Property with the same name already exists on object.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.18/System.Private.CoreLib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
...
```

and the env var set in `launchSettings.json` don't load.

### Steps To Reproduce

I don't use a `launch.json`, but run directly from "Solution Explorer" -> Debug -> Start New Instance...

A breakpoint in the `Main` method returns `Environment.GetEnvironmentVariable("NETCORE_ENVIRONMENT")` as `null`

The `Program.cs` `Main` method is:
```cs
private static async Task<int> Main(string[] args)
{
    System.Console.WriteLine($"ENV: {Environment.GetEnvironmentVariable("NETCORE_ENVIRONMENT")}.");
    await new HostBuilder()
                .UseServiceProviderFactory(new AutofacServiceProviderFactory())
                .UseEnvironment(Environment.GetEnvironmentVariable("NETCORE_ENVIRONMENT") ?? "Production")
                .ConfigureAppConfiguration((context, config) => ConfigureAppConfiguration(context, config, args))
                .ConfigureServices(ConfigureServices)
                .ConfigureLogging(ConfigureLogging)
                .ConfigureContainer<ContainerBuilder>(ConfigureContainer)
                .RunConsoleAsync();
                return 0;
}
```

The `launchSettings.json` file is:

```json
{
  "profiles": {
    "<project name>": {
      "commandName": "Project",
      "environmentVariables": {
        "NETCORE_ENVIRONMENT": "Development"
      }
    }
  }
}
```

### Expected Behavior

I would expect the env var to be `"Development"`

If running with `dotnet run --project <project name>.csproj` it correctly outputs `ENV: Development.`

### Environment Information

- OS: macOS v13.4.1
- VS Code: 1.80.0
- C# Dev Kit: v0.1.103
- C# extension: v2.0.248
- IntelliCode for C# Dev Kit v0.1.26
- .NET v6.0.18

**Comment by wjrogers** [comment]
I can't get `launchSettings.json` environment variables to work with C# Dev Kit, either. I do _not_ see the message "Unable to apply environment variable settings" in the debug log, but they do not work.

```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "<project>": {
      "commandName": "Project",
      "commandLineArgs": "",
      "environmentVariables": {
        "DOTNET_ENVIRONMENT": "Development"
      }
    }
  }
}
```

- C# v2.0.328
- C# Dev Kit v0.3.21

**Comment by rido-min** [comment]
same here

**Comment by wjrogers** [comment]
Environment variables in `launchSettings.json` still don't work for me in the latest release.
* I know VS Code can find the file because changing `commandLineArgs` works, but it completely ignores the environment variables.
* The same project works as expected, with environment variables, in both Visual Studio 2022 and on the command line with `dotnet run`.
* I do _not_ get the message "WARNING: Unable to apply environment variable settings" reported in this issue.

Maybe my problem is unrelated? Should I open a new issue?

**VSCode version**: 1.83.0
**C# Extension**: 2.4.4
**C# Dev Kit**: 0.5.150
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.401
 Commit:    eb26aacfec

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.401\

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.214 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.317 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.1.22431.12 [C:\Program Files\dotnet\sdk]
  7.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.1.22427.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.1.22426.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.1.22427.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|ansible|redhat|2.7.98|redhat.ansible-2.7.98|
|azure-repos|ms-vscode|0.38.0|ms-vscode.azure-repos-0.38.0|
|beardedicons|BeardedBear|1.13.2|beardedbear.beardedicons-1.13.2|
|black-formatter|ms-python|2023.4.1|ms-python.black-formatter-2023.4.1|
|copilot|GitHub|1.122.462|github.copilot-1.122.462|
|copilot-chat|GitHub|0.7.1|github.copilot-chat-0.7.1|
|csdevkit|ms-dotnettools|0.5.150|ms-dotnettools.csdevkit-0.5.150-win32-x64|
|csharp|ms-dotnettools|2.4.4|ms-dotnettools.csharp-2.4.4-win32-x64|
|dotnet-interactive-vscode|ms-dotnettools|1.0.4461040|ms-dotnettools.dotnet-interactive-vscode-1.0.4461040|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|isort|ms-python|2023.10.1|ms-python.isort-2023.10.1|
|jupyter|ms-toolsai|2023.9.1002771829|ms-toolsai.jupyter-2023.9.1002771829-win32-x64|
|jupyter-keymap|ms-toolsai|1.1.2|ms-toolsai.jupyter-keymap-1.1.2|
|jupyter-renderers|ms-toolsai|1.0.17|ms-toolsai.jupyter-renderers-1.0.17|
|packer|4ops|0.3.0|4ops.packer-0.3.0|
|powershell|ms-vscode|2023.6.0|ms-vscode.powershell-2023.6.0|
|prettier-vscode|esbenp|10.1.0|esbenp.prettier-vscode-10.1.0|
|python|ms-python|2023.16.0|ms-python.python-2023.16.0|
|remote-containers|ms-vscode-remote|0.309.0|ms-vscode-remote.remote-containers-0.309.0|
|remote-repositories|ms-vscode|0.40.0|ms-vscode.remote-repositories-0.40.0|
|remote-wsl|ms-vscode-remote|0.81.7|ms-vscode-remote.remote-wsl-0.81.7|
|remotehub|GitHub|0.62.0|github.remotehub-0.62.0|
|terraform|hashicorp|2.28.0|hashicorp.terraform-2.28.0-win32-x64|
|theme-dracula|dracula-theme|2.24.3|dracula-theme.theme-dracula-2.24.3|
|vim|vscodevim|1.25.2|vscodevim.vim-1.25.2|
|vscode-docker|ms-azuretools|1.26.1|ms-azuretools.vscode-docker-1.26.1|
|vscode-dotnet-runtime|ms-dotnettools|1.8.0|ms-dotnettools.vscode-dotnet-runtime-1.8.0|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-github-actions|github|0.26.2|github.vscode-github-actions-0.26.2|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscode-jupyter-cell-tags|ms-toolsai|0.1.8|ms-toolsai.vscode-jupyter-cell-tags-0.1.8|
|vscode-jupyter-slideshow|ms-toolsai|0.1.5|ms-toolsai.vscode-jupyter-slideshow-0.1.5|
|vscode-kubernetes-tools|ms-kubernetes-tools|1.3.15|ms-kubernetes-tools.vscode-kubernetes-tools-1.3.15|
|vscode-markdownlint|DavidAnson|0.52.0|davidanson.vscode-markdownlint-0.52.0|
|vscode-pull-request-github|GitHub|0.72.0|github.vscode-pull-request-github-0.72.0|
|vscode-pylance|ms-python|2023.9.30|ms-python.vscode-pylance-2023.9.30|
|vscode-tailwindcss|bradlc|0.10.0|bradlc.vscode-tailwindcss-0.10.0|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-win32-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>
