### ISSUE TITLE
Build Task Hangs when invoked from Solution Explorer

### ISSUE THREAD

**Issue by isaacrlevin** [microsoft/vscode-dotnettools#25]
Type: <b>Bug</b>

- Install C# Dev Kit on VS Code Insiders
- Create new project (any will work)
- In Solution Explorer, right-click --> build project
- dotnet build task just hangs there, not completing

Extension version: 0.1.83
VS Code version: Code - Insiders 1.79.0-insider (aee52551e25d98391f9064996196cd83a9fc8669, 2023-06-06T15:00:13.166Z)
OS version: Windows_NT x64 10.0.25375
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (34.38GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by isaacrlevin** [comment]
@timheuer VS Code doesn't seem to append setting/extension data into issues. Here is a gif of the issue. Not sure what you need to better triage
![vscode](https://github.com/microsoft/vscode-dotnettools/assets/8878502/6ade5572-2b68-4556-9eb0-85ee8a7bf98a)

**Comment by Erarndt** [comment]
@isaacrlevin , do you have any additional details about how I might be able to reproduce this issue? I've been trying to reproduce this with no success. The build process is rather simple since we just invoke dotnet.exe to build. You mentioned that it seems to be a setting or another extension that's contributing to this issue since a "clean" version doesn't exhibit this problem. If you disable the other extensions, in the problematic scenario, does the issue reproduce? You can disable extensions via the context menu in the Extensions view:

![image](https://github.com/microsoft/vscode-dotnettools/assets/60519722/7ce8ef54-253b-46ad-a994-cc646199eccd)

Happy to chat if you have any questions.
