### ISSUE TITLE
[BUG] Has something broken with IntelliSense recently?

### ISSUE THREAD

**Issue by starball5** [microsoft/vscode-dotnettools#317]
### Describe the Issue

I don't use this extension myself, but I'm fairly active as a helper on Stack Overflow and r/vscode for VS Code questions, and in the past 24 hours, I've seen multiple questions about issues with C#-related extensions.

For example, getting IDE0051 and IDE0044 errors when there shouldn't be. See ["Unity C# - Suppressing unwanted warnings in VS Code" on Stack Overflow](https://stackoverflow.com/q/76828664/11107541), and ["The official Microsoft C# for Visual Studio Code got updated and no longer support Unity" on r/vscode](https://www.reddit.com/r/vscode/comments/15hdh4p).

Some other posts I've seen on r/vscode:

- [IntelliSense not working in Visual Studio Code for C# after .NET update](https://www.reddit.com/r/vscode/comments/15haulm)
- [C# extension has problems?](https://www.reddit.com/r/vscode/comments/15gw5rn)
- [(New to coding) Started learning C# few data ago but suddenly vscode stoped autofilling for classes like console and random, even the text coloring changes. Any idea why?](https://www.reddit.com/r/vscode/comments/15h22du)
- [How do i disable Roslyn Code Analysis from the "C# Dev Kit" Extension for the whole Directory?](https://www.reddit.com/r/vscode/comments/15h27i5)
- [How do I fix this error?](https://www.reddit.com/r/vscode/comments/15h7r7h)

### Steps To Reproduce

Since I don't do C# development, I don't have any repro set up (apologies). But I can ping people / chase them down for more info. Just let me know what info to ask them for.

**Comment by smitpatel** [comment]
cc: @timheuer

**Comment by timheuer** [comment]
Hi @starball5 thanks for being a proxy for some of these.  Recently we have updated the C# extension in VS Code, and actually brought more official Unity support via a separate extension (the existing capability was a little DIY).  The ideal thing for individual experience problems is to log an issue here with some more details so we can engage with them, have trackable outcomes, and others can perhaps find similar resolutions when provided.

Specifically some of those are too generic for me to clearly identify if/what the issue is.  Others are not.  For example, the Unity one we can point to: https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/ 

I don't have a reddit account to quickly comment on those, but we'd encourage anyone specifically to use the "Report an Issue" menu option in VSCode to log an issue (gives us a bit of detail on versions, etc).

**Comment by timheuer** [comment]
Great, thanks @starball5 I'll close this one for now to yield for specifics.  Thanks again for being a great community steward of feedback. We do want to make sure we help resolve specifics.
