### ISSUE TITLE
[SUGGESTION] Can we get rid of ".NET Install Tool for Extension Authors"? since it makes this extension unuseable

### ISSUE THREAD

**Issue by NewUserHa** [microsoft/vscode-dotnettools#332]
### Describe the feature you'd like

The [.NET Install Tool for Extension Authors](https://github.com/dotnet/vscode-dotnet-runtime) extension keeps throwing
```
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.9 ...................................................................................................................... Error!
Failed to download .NET 7.0.9:
.NET installation timed out.

 Error!
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.
```
And that makes this extension totally not working/useless (since it can't start).

There're several similar issues reporting 'failed to download', those are opened for months in that "Install Tool" repo but still remain unsolved or 0 replay or not triaged, eg https://github.com/dotnet/vscode-dotnet-runtime/issues/230, https://github.com/dotnet/vscode-dotnet-runtime/issues/939, https://github.com/microsoft/vscode-dotnettools/issues/138 (the workaround in this issue dont work) and etc (these are not all).
That "Install Tool" seems to lack maintenance seriously and is also badly rated in the vscode marketplace.

May this extension get rid of that "Install Tool" extension? and use auto-detect or let the users choose dotnet? since this extension is for developers.
just like how any other language in vscode like go or python chooses their binaries, by users.

**Comment by AArnott** [comment]
We have a potential fix queued for publishing as a prerelease next week.

**Comment by ManfredLange** [comment]
@AArnott 

Why are we forced to have an extension installed that nobody asked for?

We have a dev container that we definitely do not use for extension development. We are very particular about the .NET runtime we want to be present in that dev container. We do this to minimize the variability that otherwise can cause the well-known "works on my machine" effect.

We do not want any other party, e.g. Microsoft, to overwrite that decision and install whatever .NET runtime they deem the right one for us. In essence, be falling bad into the dark ages of Microsoft behavior and force-feeding users with what you think is the right thing, you force us to go back on our quality practice.

Not a good move at all, but perhaps I am overlooking something here ....

**Comment by AArnott** [comment]
I'll add that the recent change with which I closed this issue makes C# Dev Kit first try to use a .NET 7 runtime that it can already find on the box (or your container, in your case) before installing a private copy. That can make your first use a little faster because we don't download an extra copy. We'll still fallback to installing a private, isolated .NET 7 runtime if we can't find a compatible one already on the box.

In the near future though, largely because of the negative impression so many customers have of this pattern (which IMO is partly due to misunderstanding what it is and how it works), and also because of reliability problems with downloading and unzipping an app-local runtime for the extension, we plan to switch our fallback plan to installing a machine-global runtime. That is, if you don't already have .NET 7 installed, we'll install it globally, requiring elevation. I have mixed feelings about this, because like you, I'd rather we not mess with the machine environment. But we really need to improve reliability and this is the best way we know to get it. I can explain more if you're interested in this.

**Comment by NewUserHa** [comment]
> we plan to switch our fallback plan to installing a machine-global runtime.

Why can't developers take care of their environment by themselves?  Adding another black box messing with the env will confuse new beginners even more I think. 

This is only a vscode extension (even not a customer/end-user extension) and ppl want just feature "Package Management" and etc. from this extension.

If you want to make new beginners feel better on installing .NET or installing extensions for vscode, in my opinion, a new independent extension can be better. it will let the users choose whether to install the extension.

**Comment by AArnott** [comment]
> Why can't developers take care of their environment by themselves?

They certainly can. If they already have .NET 7 installed, the plan is to reuse it. If they don't, they'll be told it's required to run the extension, and we'll assist in installing it or the user can opt to install it themselves.

> If you want to make new beginners feel better on installing .NET or installing extensions for vscode, in my opinion, a new independent extension can be better

Can you elaborate on this? What would this new extension do? We have C# Dev Kit and the .NET acquisition extension as two distinct extensions, so do you mean we should subdivide it further into 3 somehow?

**Comment by NewUserHa** [comment]
> They certainly can. If they already have .NET 7 installed, the plan is to reuse it. If they don't, they'll be told it's required to run the extension, and we'll assist in installing it or the user can opt to install it themselves.

If it's "if .net7 not found then ask if need help to install" then it looks good to me.

> Can you elaborate on this? What would this new extension do? We have C# Dev Kit and the .NET acquisition extension as two distinct extensions, so do you mean we should subdivide it further into 3 somehow?

It was for "if forcing installing globally without asking". Then it could be a bootstrap extension for beginners addition with some tutorials maybe. And non-beginners also can utilize it via a URL in the readme of this extension rather than a bundle if they don't want to install runtime/sdk manually.
But if it asks before to help install then probably ppl is ok with a dependency of install helper.

**Comment by AArnott** [comment]
Yes, we have a walkthrough that will help users understand what is required and a button that the user may choose to click to start the .NET runtime/SDK installer.
