### ISSUE TITLE
Create sln files only on demand

### ISSUE THREAD

**Issue by arambazamba** [microsoft/vscode-dotnettools#357]
### Describe the feature you'd like

c# dev kit creates sln files for every project one opens in vscode ... I want the ability to disable this behaviour by default and have to sln file create when require it to be create using the command palette.

the reason behind this is that I sometimes open projects that might be part of a solution in its own vscode instance. with the current behavior projects that are part of a solution have their own solution file that I need to delete

### Environment Information

-OS: Windows 11

**Comment by arambazamba** [comment]
Especially when you opened a subfolder with 2-3 projects that you focus on and a higher level parent folder has already a sln file

**Comment by ocdi** [comment]
> Especially when you opened a subfolder with 2-3 projects that you focus on and a higher level parent folder has already a sln file. Everything gets messed up

This 100% - we have multiple C# projects that we may want to have in a microservice. It breaks the intellisence system because you need to pick a particular project to be the main solution. This goes against what we have been doing in VSCode for years. It needs to support multiple solutions.

I also have a .net Azure Function that has `extensions.csproj` that also confuses this extension. We do not want a .sln created for this each time this folder is opened.

**Comment by arambazamba** [comment]
@ocdi 💯 VS Professional Developers open Solutions, VS Code Devs open folders that might contain projects and solutions nested in different hierarchies… Especially for Cloud Native Apps

**Comment by bruce31** [comment]
@arambazamba @ocdi I uninstalled the extension as soon as I realised it was creating .sln files without asking. Totally unacceptable behaviour in VSCode. I frequently use VSCode to open individual projects within a large solution and creating .sln files really messes things up.

**Comment by arambazamba** [comment]
@bruce31 same here … once I found out, I uninstalled

**Comment by bruce31** [comment]
@arambazamba Good News. There is a setting to prevent automatic creation of solution files.
```json
"dotnet.automaticallyCreateSolutionInWorkspace": false
```
This can be set at user level so that it applies to all workspaces you create. Also can be set for an individual workspace.  
I have now re-installed the extension and so far it seems to have stopped creating .sln files

Found link to https://github.com/dotnet/extensions/pull/4509#issuecomment-1748236445 in discussion of  
[SUGGESTION] Option to disable solution integration https://github.com/microsoft/vscode-dotnettools/issues/395 

We may be able to close this
