### ISSUE TITLE
[BUG] Unable to build IPA

### ISSUE THREAD

**Issue by Manchy8** [microsoft/vscode-dotnettools#373]
### Describe the Issue

After successfully publishing my project archive many times on my Mac I am now not able to.   

Using the following CLI command:
 
dotnet publish -f:net7.0-iOS -c:Release   /p:RuntimeIdentifier=ios-arm64   /p:ServerAddress=192.168.143.51 /p:ServerUser=danielmanchester /p:ServerPassword=xxx /p:TcpPort=58181  /p:DotNetRootRemoteDirectory=/Users/danielmanchester/Library/Caches/Xamarin/XMA/SDKs/dotnet/ /p:CodesignKey="Apple Distribution :xxxx"  /p:CodesignProvision="MobileMauiSigning" -bl:output17.binlog

I get the following error

C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk\16.4.7067\tools\msbuild\iOS\Xamarin.Shared.targets(1746,3): error : Could not find Microsoft.iOS in /usr/local/sha
re/dotnet/packs/Microsoft.iOS.Sdk/16.4.7067/. [C:\Users\Danie\Documents\GitHub VS\MAUI\Mobile\ChronicleMobile\ChronicleMobileApp\ChronicleMobileApp.csproj::Target
Framework=net7.0-iOS]

What do I need to do to fix this?

Thanks

### Steps To Reproduce

See the description above.

### Expected Behavior

IPA would be created as a result of CLI publish command.

### Environment Information

Windows 11
VS 17.6.5

**Comment by mancda** [comment]
What happens if on my Mac I have Microsoft.iOS version  16.4.7090 but on my windows machine my project when building is looking for 16.4.7089 ?  If this is a problem, and I believe it is, what is the best way to make them a match up ?

**Comment by emaf** [comment]
There are 2 options:
1. You can open your project on Visual Studio and connect to your Mac using Pair to Mac. It will automatically update the SDK version on the Mac to match what's on Windows. 
2. You can manually update the .NET SDK and the iOS workload installed under `~/Library/Caches/Xamarin/XMA/SDKs/dotnet` using the CLI.

If you face any problems with the first option I'd recommend you to report an issue from Visual Studio, and for any CLI related issues with Microsoft.iOS you can open an issue on https://github.com/xamarin/xamarin-macios, which is where that SDK lives, so the right set of folks can help you.

I'm closing this issue since this isn't related to the .NET MAUI extension for VS Code, but to the Microsoft.iOS SDK.
