### ISSUE TITLE
C# Compilation Errors Not Recognized Until File Opened

### ISSUE THREAD

**Issue by lcompton** [microsoft/vscode-dotnettools#401]
Type: <b>Bug</b>

1. Install Unity extension in VS Code
2. Configure a Unity project to use VS Code per extension instructions
3. Configure C# extension in VS Code such that both Dotnet Background Analysis settings are set to "fullSolution", do this for both User and Workspace
3. Create severlal C# scripts one of which should contain compilation errors
4. Close VS Code
5. Open a working C# scipt from Unity

Actual Result
Script with errors is not highlighted in red, until it is opened.

Expected Result
Script name should be highlighted in red and errors should listed in "PROBLEMS"

Extension version: 0.9.0
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
2e4cg342:30602488
f6dab269:30613381
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30812749

```

</details>

**Comment by sailro** [comment]
Initial discussion here:
https://forum.unity.com/threads/unity-extension-for-visual-studio-code-compilation-errors-suppressed-until-you-open-file.1479795/#post-9227469

Unity - 2023.1.8
VSCode - 1.81.1
C# Extension - 2.0.366
C# Dev Kit - 0.4.2
Unity Extension for Visual Studio Code - 0.9.0

**Comment by sailro** [comment]
Are you participating in the project generation? (like having Editor scripts using `AssetPostprocessor.OnGeneratedCSProject`). 

The other interesting think is "Hundreds of errors are cited having to do with System.Void, System.int32, etc. not being found. None of the errors are cited by Unity.". Perhaps an issue we the `TargetFramework` we use for all profiles: `netstandard2.0`, but this should no be an issue (even if you are using the net48 profile). Any specific hack you use around the API surface ? like putting System/Unity dlls directly in your `Assets` folder?

Any chance you can share the whole project privately with us? I think you can have something specific that is causing the issue. The first step is to be able to build successfully outside Unity.

**Comment by lcompton** [comment]
I managed to recreate the problem in a separate project that I can share with you. What's the best way to get it in your hands?

All I had to do was install Mirror, a popular multiplayer library...
- https://mirror-networking.com/

It adds quite a few "csproj" and "asmdef" files. VS Code behaves as I described... very inconsistent. It will find an error in one of my scripts, but only if it finds a ton of problems in the Mirror code first (which aren't actually problems according to Unity) or if you open the file containing the error.

I'm not doing anything exotic in the project generation process nor have I fiddled around with DLL placement. I let Unity handle that.

**Comment by sailro** [comment]
> I managed to recreate the problem in a separate project that I can share with you. What's the best way to get it in your hands?
> 
> All I had to do was install Mirror, a popular multiplayer library...
> 
> * https://mirror-networking.com/
> 
> It adds quite a few "csproj" and "asmdef" files. VS Code behaves as I described... very inconsistent. It will find an error in one of my scripts, but only if it finds a ton of problems in the Mirror code first (which aren't actually problems according to Unity) or if you open the file containing the error.
> 
> I'm not doing anything exotic in the project generation process nor have I fiddled around with DLL placement. I let Unity handle that.

Thank you for this repro, you can send it to us using vstusp[at]microsoft[dot]com

**Comment by lcompton** [comment]
[VSCodeTest.zip](https://github.com/microsoft/vscode-dotnettools/files/12369771/VSCodeTest.zip)

Here's the project. I tried emailing it and Gmail refused to send it.

**Comment by lcompton** [comment]
One minor difference I should mention. The repro project is using Unity 2023.1.9 as opposed to 2023.1.8. I don't think that matters.

Good luck figuring this out! Let me know if you need anything else from me. I want you to succeed. I really don't want to change IDEs.

**Comment by sailro** [comment]
So I repro the issue using your project.

What I'm seeing so far:

- When generating `legacy-style` projects (like when setting `VS` as your external editor)
  - Everything is building fine in `VS` or `CLI`.
  - It will not work with `VSCode` given `C# Dev Kit` is compatible with `SDK-Style` projects only.

- When generating `SDK-Style` projects (like when setting `VSCode` as your external editor)
  - Sometimes it compiles fine, sometimes the compilation breaks. No real explicit trigger for now (tried to repro after clean, etc.).
  - Repro with `VS`, `VSCode` and `CLI`.
  - When the compilation fails we have the following:
 ```terminal
error MSB4006: There is a circular  dependency in the target dependency graph involving target "CleanReferencedProjects". [C:\dev\VSCodeTest\Mirror.CompilerSymbols.csproj]
```

**Comment by sailro** [comment]
I found something interesting, @lcompton could you try the following:

- remove all generated csproj/sln
- In Unity, set Editor Compatibility Level to `.NET Standard`
![image](https://github.com/microsoft/vscode-dotnettools/assets/638167/a04be97a-9b42-4761-9353-5b4c3c54ecd7)
- In `Asset/Preference/External tools`, click `Regenerate project Files`
- Use `Assets/Open C# Project`

It seems to work on my side.

My gut feeling is that this `MSB4006` is the result of Editor assemblies using .net framework references.

**Comment by lcompton** [comment]
I followed the directions (there were a few errors, btw) but it didn't work. See below...

![Untitled](https://github.com/microsoft/vscode-dotnettools/assets/7620502/49910e52-5569-4179-9891-e925d0f8e2df)

**Comment by sailro** [comment]
> there were a few errors in the directions, btw

"there were a few errors in the directions, btw" => just to be sure we are on the same page, could you elaborate on those errors in the directions ?

**Comment by lcompton** [comment]
Sure. There wasn't anything major, I just had to hunt down some of the settings...

1. "Editor Assemblies Compatibility Level" is found in "Project Settings", not "Build Settings"
2. "External Tools" is found in "Edit->Preferences", not "Assets->Preferences"

Now, if I didn't actually change them in the right place, let me know and I will try again.

**Comment by jbevain** [comment]
Ok so there are two different problems, which might be related.

1. The compilation of the Repro project hits a race in msbuild on the .NET 7 SDK. I can run `dotnet build` on the .sln multiple times and sometime get the circular dependency error, or sometimes it would build, without touching anything.
2. Even though the `C#` extension is set to analyze the full solution in the background, it doesn't report the errors for all the files before they are opened.

It's very possible that 1 is triggering 2.

I'm going to extract a standalone repro that doesn't depend on a Unity install for the MSBuild team so we can investigate. We need to see if we can repro issue 2. in a simple repro that doesn't hit 1.

**Comment by assarbad** [comment]
>       * When the compilation fails we have the following:
> 
> 
> ```
> error MSB4006: There is a circular  dependency in the target dependency graph involving target "CleanReferencedProjects". [C:\dev\VSCodeTest\Mirror.CompilerSymbols.csproj]
> ```

Hi there, don't know if this will be of help to anyone, but I'll give it a shot. I have gotten the same `MSB4006` error in a project which tries to mimic a VC++ project (but has its `DefaultTargets` set to the only relevant target -- named `ClVersionRetrieve` -- within that project).

It turns out when I tell MSBuild to use that specific target, everything works as expected.

However, when I use `Rebuild` as the target, I suddenly get the above error. I used the `msbuild -pp` method to see the preprocessed form of the project and looking at that one can see a property `RebuildDependsOn`. That property contains the dependencies of the `Rebuild` target and they differ depending a property `_ProjectDefaultTargets` which gets populated from `$(MSBuildProjectDefaultTargets)` or defaults to `Build`. Here's what `RebuildDependsOn` receives depending on `$(MSBuildProjectDefaultTargets)`:

```
<RebuildDependsOn>
  BeforeRebuild;
  Clean;
  $(_ProjectDefaultTargets);
  AfterRebuild;
</RebuildDependsOn>
<RebuildDependsOn Condition=" '$(MSBuildProjectDefaultTargets)' == 'Rebuild' ">
  BeforeRebuild;
  Clean;
  Build;
  AfterRebuild;
</RebuildDependsOn>
```

Once I noticed that, I figured that for my specific project I have no need for `Clean` anyway and so decided to override it (== empty it out) within my own project like this:

```
	<Target Name="Clean" />
```

The effect is that the circular dependency vanishes.

Of course in your case another action may be more appropriate. But by selectively "canceling" individual targets which are within the dependency graph (i.e. emptying them and decoupling them by not providing `BeforeTargets` and `DependsOnTargets` attributes) may help resolve this. `msbuild --targets` may also be of help, unfortunately `msbuild -graph` does not help, because [it bails out due to the circular dependency](https://github.com/dotnet/msbuild/issues/9276) (` MSB4251: There is a circular dependency involving the following projects:`). Target graphs would be _the_ ideal tool to investigate this sort of issue, if they were being created despite the existence of a circular dependency.

It may also be of help to specify `msbuild -verbosity:diagnostic` when investigating issues such as this one.

**Comment by jbevain** [comment]
We've identified the source of the circular dependency error when generating projects and are working on a fix.

**Comment by sailro** [comment]
As a temporary workaround, you can create a `Directory.Build.props` file in your Unity project (so among with `csproj` files) with the following content:
```xml
<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>Temp/obj/$(Configuration)/$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <IntermediateOutputPath>$(BaseIntermediateOutputPath)</IntermediateOutputPath>
  </PropertyGroup>
</Project>
```

**Comment by SAKryukov** [comment]
`BaseIntermediateOutputPath`:

It looks like VSCode .NET extension has a problem when `BaseIntermediateOutputPath` is modified. I always modify this path, as well as `OutputPath` in Directory.Build.props, because it helps to isolate source code from intermediate files and outputs.

The only problem is the task `dotnet: build`. It creates intermediate files according to `BaseIntermediateOutputPath`, but also in the default location. Naturally, auto-generated .cs files are placed in two locations, they are compiled and create the clash, compilation error due to double definitions.

The simplest workaround is this: instead of using `dotnet: build` use the task:
~~~
{
    "label": "incrementalBuild",
    "type": "shell",
    "command": "dotnet build",
    "presentation": {
        "reveal": "always",
        "panel": "shared"
    }
}
~~~
Everything works then, including error presentation and handling
