### ISSUE TITLE
Tests are removed from test explorer after changes to test files

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#460]
### Describe the Issue

Originally reported by @niklaswallerstedt at https://github.com/dotnet/vscode-csharp/issues/6219

## Issue Description ##
Using XUnit when I've made changes to a test file the test explorer loses track of that project whenever I try to run the test suite. I need to press `Run Test` twice.

## Steps to Reproduce ##
Created a reproduction repo -> https://github.com/niklaswallerstedt/vscode-csharp

1. Open project in VSCode
2. Open the Test explorer/pane
3. Click `Run Test`

## Expected Behavior ##
The test suite should be present even after changing any test files

## Actual Behavior ##
The test suite is removed.

```shell
Tests removed: /Users/niklaswallerstedt/Development/reproduction/vscode-csharp/tests/vscode-sharp.Tests/bin/Debug/net7.0/vscode-sharp.Tests.dll
Tests are available, running test discovery: /Users/niklaswallerstedt/Development/reproduction/vscode-csharp/tests/vscode-sharp.Tests/bin/Debug/net7.0/vscode-sharp.Tests.dll
========== Starting test discovery ==========
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 7.0.5)
[xUnit.net 00:00:00.28] Discovering: vscode-sharp.Tests
[xUnit.net 00:00:00.31] Discovered: vscode-sharp.Tests
========== Test discovery finished: 1 Tests found in 672,6 ms ==========
========== Starting test run ==========
========== Test run finished: 0 Tests (0 Passed, 0 Failed, 0 Skipped) run in < 1 ms ==========
```

**Comment by ekaradzha-qb** [comment]
Same here.

**Comment by ocallesp** [comment]
Started to check this issue

**Comment by ocallesp** [comment]
@niklaswallerstedt

I couldn't replicate this issue using the provided steps for reproduction. Is there a step I might be overlooking?

![CannotRepro](https://github.com/microsoft/vscode-dotnettools/assets/510598/20d6654b-beca-4d9a-8047-397ed3c0a286)

**Comment by niklaswallerstedt** [comment]
It seems it is indeed working for you, here's my screenshare. Happy to help getting to the bottom of this as this is a source of frustration 😄 Anything I can share to troubleshoot this?


https://github.com/microsoft/vscode-dotnettools/assets/2744846/b38c6267-5c59-4fce-b802-452762c1cd67

**Comment by niklaswallerstedt** [comment]
@ocallesp Is this a Mac specific issue?

**Comment by niklaswallerstedt** [comment]
@ekaradzha-qb which OS are you using?

**Comment by ocallesp** [comment]
I couldn't repro this issue on my mac machine.

What I see different is that instead of

Tests removed: /Users/niklaswallerstedt/Development/reproduction/vscode-csharp/tests/vscode-sharp.Tests/bin/Debug/net7.0/vscode-sharp.Tests.dll
Tests are available, running test discovery: /Users/niklaswallerstedt/Development/reproduction/vscode-csharp/tests/vscode-sharp.Tests/bin/Debug/net7.0/vscode-sharp.Tests.dll
========== Starting test discovery ==========

I see a
 
Tests **changed**, running test discovery: /Users/niklaswallerstedt/Development/reproduction/vscode-csharp/tests/vscode-sharp.Tests/bin/Debug/net7.0/vscode-sharp.Tests.dll
========== Starting test discovery ==========

@ekaradzha-qb @niklaswallerstedt
sounds like during build this dll is updated, but in the issue this dll is removed and then added. Not sure if this is related to the filesystem or the api that watches this dlls.
What type of filesystem are you using ?

@peterwald
It seems that a fix can be to ignore all these notifications during build, and check them all after the build.

**Comment by niklaswallerstedt** [comment]
@ocallesp I'm on a Mac M1 using APFS

**Comment by peterwald** [comment]
Fix merged. Will be fixed in the next release.

**Comment by niklaswallerstedt** [comment]
@peterwald and others thanks for fixing this 🥳 can confirm that it's working as expected now.
