### ISSUE TITLE
[BUG] Debugger is terminated when adding a folder to the workspace

### ISSUE THREAD

**Issue by wendellestradairely** [microsoft/vscode-dotnettools#499]
### Describe the Issue

The debugger is terminated when adding a folder to a workspace.
![image](https://github.com/microsoft/vscode-dotnettools/assets/50942719/d7db2d65-426d-422a-9d39-504029f42094)

Error: "Debug adapter process has terminated unexpectedly (Extension host shut down)"

![image](https://github.com/microsoft/vscode-dotnettools/assets/50942719/1de3a71d-d4b4-4730-8d94-a36d8a7bbcbf)

### Steps To Reproduce

1. Open a ASP.NET 6+ project.
2. Click File -> Add Folder to Workspace...

### Expected Behavior

Should not terminate the debugger.

### Environment Information

Version: 1.81.1 (user setup)
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:22:42.175Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by WardenGnaw** [comment]
This error message comes from VS Code at https://github.com/microsoft/vscode/blob/ecb0c80fc1da718cabb863409897d941bf18aa49/src/vs/workbench/contrib/debug/browser/debugService.ts#L678 

This is the call stack (it is minified because its all in release VS Code code).

c (notificationsAlerts.ts:42)
(anonymous) (notificationsAlerts.ts:28)
w (event.ts:1089)
x (event.ts:1100)
fire (event.ts:1124)
addNotification (notifications.ts:204)
error (notificationService.ts:130)
(anonymous) (debugService.ts:678)
w (event.ts:1089)
x (event.ts:1100)
fire (event.ts:1124)
W (debugSession.ts:1263)
(anonymous) (debugSession.ts:1256)
w (event.ts:1089)
fire (event.ts:1120)
M (rawDebugSession.ts:639)
L (rawDebugSession.ts:624)
await in L (async)
K (rawDebugSession.ts:607)
await in K (async)
(anonymous) (rawDebugSession.ts:97)
w (event.ts:1089)
fire (event.ts:1120)
fireError (mainThreadDebugService.ts:420)
(anonymous) (mainThreadDebugService.ts:55)
(anonymous) (lifecycle.ts:197)
(anonymous) (functional.ts:17)
l (lifecycle.ts:150)
clear (lifecycle.ts:252)
dispose (lifecycle.ts:233)
dispose (mainThreadDebugService.ts:123)
dispose (extensionHostManager.ts:196)
pb (abstractExtensionService.ts:643)
qb (abstractExtensionService.ts:682)
await in qb (async)
stopExtensionHosts (abstractExtensionService.ts:628)
enterWorkspace (workspaceEditingService.ts:157)
createAndEnterWorkspace (abstractWorkspaceEditingService.ts:253)
await in createAndEnterWorkspace (async)
t (abstractWorkspaceEditingService.ts:189)
addFolders (abstractWorkspaceEditingService.ts:167)
handler (workspaceCommands.ts:72)
await in handler (async)
invokeFunction (instantiationService.ts:68)
k (commandService.ts:95)
executeCommand (commandService.ts:60)
(anonymous) (menubarControl.ts:643)
run (actions.ts:158)
k (actions.ts:194)
run (actions.ts:185)
onClick (actionViewItems.ts:170)
(anonymous) (menu.ts:499)
setTimeout (async)
(anonymous) (menu.ts:498)

Next steps are this is either on VS Code or something in C# DevKit or C# Extension is handling workspace changes and causing this error to occur.

Moving to area-project-cps

**Comment by Michael-Eng** [comment]
@lifengl I think it's reasonable to restart if the user does multi-root but do we need to do more to tell the user?

**Comment by lifengl** [comment]
does this happen during the time adding a folder to a single root workspace to make it multi-root workspace? That would basically switch to a new (newly created workspace), and the entire extension process tree would be killed by vscode when workspace is changed. The extension has a very short time to handle it before it is hard killed. I am not sure we can do much here.

another possibility is the extension is enabled only on trusted workspaces, when a new folder is added, it could change whether the workspace can be trusted, so the extension may be unloaded.
