### ISSUE TITLE
[BUG] Multiple instances of .NET host, hogging more than 95% memory and CPU

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#518]
### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/6344

## Issue Description ##
Multiple instances of .NET process. We have 42 csproj in our microservices-based solution. And every time I build the solution, the multiple .NET process gets spawned hogging up 95% of the CPU. And after building the instances do not get disposed of or close, they just sit there on RAM without any reason hogging up RAM as well. 
I would suggest please find a better way to reuse the instances of the .NET host to build the solution and to keep some data between the builds so that we can stop building unchanged projects just like Visual Studio. Because spinning up the process every time does not look viable solution in the long run. Below are the screenshots. If you see closes the CMD instances are still there, I guess we can shut them once the build is complete just like .NET process. 

<details>

When building.
![image](https://github.com/dotnet/vscode-csharp/assets/17148381/a5df1393-e294-422f-bc83-9f0d04ecc48e)
After the build is done. 
![image](https://github.com/dotnet/vscode-csharp/assets/17148381/d6efb792-790e-406f-8014-898387bd1073)

</details>

## Expected Behavior ##
.NET instances should be reused to build projects and should get closed once done. 

## Actual Behavior ##
Multiple instances are spawned and does not get disposed. 

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.82.0
**C# Extension**: 2.1.2
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
Error running dotnet --info: Error: Command failed: C:\Program Files\dotnet\dotnet.exe --info
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|csdevkit|ms-dotnettools|0.4.10|ms-dotnettools.csdevkit-0.4.10-win32-x64|
|csharp|ms-dotnettools|2.1.2|ms-dotnettools.csharp-2.1.2-win32-x64|
|darker-dark|XavierNaves|1.0.0|xaviernaves.darker-dark-1.0.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|errorlens|usernamehw|3.13.0|usernamehw.errorlens-3.13.0|
|gitlens|eamodio|14.3.0|eamodio.gitlens-14.3.0|
|powershell|ms-vscode|2023.9.1|ms-vscode.powershell-2023.9.1|
|sonarlint-vscode|SonarSource|3.21.0|sonarsource.sonarlint-vscode-3.21.0-win32-x64|
|vim|vscodevim|1.26.0|vscodevim.vim-1.26.0|
|vscode-autohotkey2-lsp|thqby|2.1.5|thqby.vscode-autohotkey2-lsp-2.1.5|
|vscode-conventional-commits|vivaxy|1.25.0|vivaxy.vscode-conventional-commits-1.25.0|
|vscode-dotnet-runtime|ms-dotnettools|1.7.2|ms-dotnettools.vscode-dotnet-runtime-1.7.2|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64|;

</details>

**Comment by adrianvmsft** [comment]
@Michael-Eng I replied to the original issue with more details.
To summarize - not all dotnet processes are caused by build, some of them are used by the extension itself.

Likely, the dotnet process that uses more memory (1.6 Gb) represents the project system, and memory usage seems consistent with current patterns based on the number of projects in the solution.

It is expected that the project system will consume more CPU as it reacts to changes to the projects. Such changes can also be triggered by files changing on the disk (for example, if the build output folders are accidentally included by globs, they could trigger work in the project system as result of the build operation).
That work should settle once those changes are processed.

**Comment by lifengl** [comment]
Are you sure this is project-system related process? Project system is usually host inside ServiceHost process, not using dotnet directly. Most dotnet processes are msbuild related process, but those consuming large memory are typically language service one.

**Comment by lifengl** [comment]
It is process memory usage during loading OrchardCore, the memory usage of project system process is high, but the language service one is far worse.
![image](https://github.com/microsoft/vscode-dotnettools/assets/11638466/5313f758-aa92-4832-9f09-d0b08ee4e196)

**Comment by adrianvmsft** [comment]
@lifengl You are right, the project system process has a different name.
In that case it is likely roslyn process that is using resources.

**Comment by dibarbet** [comment]
Note the specific complaint was about the processes being spawned by the build sticking around after the build completes.  The roslyn process is always active and not spawned by the build.  

> And every time I build the solution, the multiple .NET process gets spawned hogging up 95% of the CPU. And after building the instances do not get disposed of or close, they just sit there on RAM without any reason hogging up RAM as well.

**Comment by Michael-Eng** [comment]
The msbuild backend node processes will exit but those are (a) controlled by msbuild and (b) deliberately kept around for a little while to save time if another build is initiated.

**Comment by rjgotten** [comment]
> The msbuild backend node processes will exit but those are (a) controlled by msbuild and (b) deliberately kept around for a little while to save time if another build is initiated.

![image](https://github.com/microsoft/vscode-dotnettools/assets/442808/2b661b5a-6b80-4402-adfd-a3483073af13)

Then something is utterly and completely broken, because this is what I get from a solution configured with
`"dotnet.backgroundAnalysis.analyzerDiagnosticsScope": "openFiles"`; _NO_ actual files open; and after 15 minutes of waiting.

**Comment by YafeshanUnal** [comment]
I'm getting the same error, I've been using etc code as .Net development for a long time and as far as I can find [C#](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) why this extension causes 7,8 gb of ram usage in my own project

**Comment by itsc-Hohmann** [comment]
I experienced the same problem. Several .NET Hosts eating 100% CPU. No application was doing any serious work at that time. Like ghost processes doing something. I rebooted the system to solve this.

**Comment by lifengl** [comment]
there are multiple issues mentioned in this thread. While on the surface, it is talking about the excessive number of dotnet hosting processes, the main problem is that those processes are using excessive memory.

Unfortunately, there are multiple different dotnet hosting processes, in the screen shot provided by @rjgotten earlier, there is one hosting process using more than 6G memory, and many others are using less than 40M memory. The problem is that the number of processes is inflated because of the extra number of msbuild node processes. During build, the number of those processes is related to the number of cores (or hyper-thread cores), so with a relatively new machine, it could be easily 12 processes created. After build, they will stay alive for 15 minutes. This is the same behavior if you build a project on command line, or build in OminiSharp.  Most of those processes will hold small amount of memory during this idle waiting, so the reason why we didn't hear complains of extra number of processes after command line build is that this thread was brought up not really because of the number of processes instead of the excessive memory usage, which is mostly coming from a single process hosting the language service. @dibarbet -- which I think Roslyn team need take a look.

Now, there is another problem: we can see some build nodes which use more than 40M memory but far less then the language service process.  In the screenshot, we can see that we have 4 of them using around 100M in @rjgotten 's screenshot, and around 350M in another one.  Those are design time build nodes started by the C# Dev Kit, which looked similar to other build nodes (which are started for building source code, and the number is about to match the number of cores (logic cores) on the machine, but they are driven by two build logic. There is a bug in C# Dev Kit that it holds those nodes, instead of releasing them. We will work a fix on that. With that fixed, those nodes may still keep alive for 15 minutes, but likely with less memory (around 40M) or in some cases (depending on timing), they might be reused by a later build session, so the number of processes might be slightly less.  But as I mentioned, this would just be a minor reduction, and would not address the main reason of the memory issue -- which as I mentioned, the number of processes is actually misleading and causes the real problem not to be tracked correctly.

**Comment by lifengl** [comment]
I believe I was wrong yesterday to think Dev Kit would leave the build open. those builds are closed, it happens the background process would take some time, after that it would take another 15 minutes, so they exit quite late.  Even if we don't build the solution, NuGet restore would start the same number of build nodes. Those two builds are running at the same time, so they won't share any build node process, which would likely leave the number of logic cores + 4, so on a modern laptop, it could start 16 processes.  There are a few other processes hosting inside dotnet. However, all those build nodes do not hold lots of memory, and will quite eventually as expected.  The number of those processes are independent to the memory issue mentioned here as well. Based on that, I think this extra number of build node processes is by design.

**Comment by FairplexVR** [comment]
I also get that problem when more than 1 project are loaded.

![Screenshot_4](https://github.com/microsoft/vscode-dotnettools/assets/31825109/f64a7a73-17f6-4736-a1ba-57aa00ac9968)

- Constant 20-25% of CPU usage
- Massive RAM Usage (4GB-8GB)
- **"dotnet.backgroundAnalysis.compilerDiagnosticsScope": "fullSolution" is totally broken** which means that Roslyn is unable to detect errors outside of opened scripts.

If I edit the Microsoft Visual Studio Solution File to remove everything except 1 project, then CPU, RAM, and Roslyn Analyzers works as expected. 

I hope this info will be useful to fix this issue.

**Comment by dangducthinh** [comment]
Same issues with @rjgotten .
![image](https://github.com/microsoft/vscode-dotnettools/assets/34974526/a20f77ab-75fc-4c9f-8692-704d6343295d)

my laptop has 32GB ram and vs code take the most of it.

**Comment by SnowPowerCore** [comment]
+1 getting a bunch of .NET hosts spawned for my .NET 8 solution, that consists of 56 projects.
![image](https://github.com/microsoft/vscode-dotnettools/assets/35460261/6ea69527-d440-44c2-89b1-f7b26a237668)

**Comment by rjgotten** [comment]
@adrianvmsft 
Can we please get something of a timeline here on what (if anything) to expect to come out of this by when?
It's been half a year and counting sofar without an effective resolution.
You'd think the new VSCode .NET Tools being untenable resource-suckers easily capable of gobbling up beyond stupid amounts of RAM if left unchecked, as now also clearly evidenced by https://github.com/microsoft/vscode-dotnettools/issues/518#issuecomment-1880448622, would have lead to some kind of prioritized investigation into the matter.

As it stands, this makes the product close to unusable.

**Comment by FairplexVR** [comment]
the actual "solution" is to keep the older version *1.26.0** and block the updates of this extension

**Comment by arkalyanms** [comment]
Splitting this into 2 bugs:
- Multiple instance of .NET host/original bug. This will continue to track designtime builds and tweaking of the process lifetimes to be moved to msbuild. We ll use this bug and transfer it to the msbuild repo. 

For the background analysis in Roslyn, it will be tracked by https://github.com/dotnet/vscode-csharp/issues/6998

**Comment by ShreyasJejurkar** [comment]
Till the time, gets fixed, or at least we hear something on this, people can set the env `MSBUILDDISABLENODEREUSE` variable to value `1`. This will shut down the instances of MSBuilds once their corresponding work is done. 

With Powershell, u can set the env variable like below. 

```powershell
$env:MSBUILDDISABLENODEREUSE=1
```

**Comment by cesare-marasco** [comment]
Hi all,
$env:MSBUILDDISABLENODEREUSE=1 doesn't solve the problem at all ! I'm really sad to say that in the latest two years visual studio it has gotten significantly worse (i fight  every day against a lot of bug) but this one it's really incredible. I have serious difficult to work in this situation because, as you can see in ![Screenshot 2024-05-22 212454](https://github.com/microsoft/vscode-dotnettools/assets/144238665/7304f040-59db-4488-a2b1-cedc60cb841d) the clones of .NET Host process eat all RAM (32 Gb) and CPU.

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.9.7

**Comment by cesare-marasco** [comment]
> Hi all, $env:MSBUILDDISABLENODEREUSE=1 doesn't solve the problem at all ! I'm really sad to say that in the latest two years visual studio it has gotten significantly worse (i fight every day against a lot of bug) but this one it's really incredible. I have serious difficult to work in this situation because, as you can see in ![Screenshot 2024-05-22 212454](https://private-user-images.githubusercontent.com/144238665/332934618-7304f040-59db-4488-a2b1-cedc60cb841d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDY4MDgsIm5iZiI6MTcxNjQwNjUwOCwicGF0aCI6Ii8xNDQyMzg2NjUvMzMyOTM0NjE4LTczMDRmMDQwLTU5ZGItNDQ4OC1hMmIxLWNlZGM2MGNiODQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxOTM1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWIwNjI5ODk4NjQzMmVjNzRhMDNlNzQ2YTcxN2RlNWExYzRiM2UzYmY1ZDljMDU2MDgwNTUzZjZmNDJmMjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3VZxF19n2wRRrXoz49eVFQYL-QcKCBnjWyiztta0NOo) the clones of .NET Host process eat all RAM (32 Gb) and CPU.
> 
> Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.9.7

If nothing changes in the next weeks and after years of use I'm thinking of abandoning visual studio

**Comment by edgett** [comment]
This is happening to me in Visual Studio 2022. I will attempt $env:MSBUILDDISABLENODEREUSE=1 and follow up.

![image](https://github.com/microsoft/vscode-dotnettools/assets/12544536/b0433174-d95b-4cff-984c-1b5a3c3d802e)

**Comment by edgett** [comment]
> > Hi all, $env:MSBUILDDISABLENODEREUSE=1 doesn't solve the problem at all ! I'm really sad to say that in the latest two years visual studio it has gotten significantly worse (i fight every day against a lot of bug) but this one it's really incredible. I have serious difficult to work in this situation because, as you can see in ![Screenshot 2024-05-22 212454](https://private-user-images.githubusercontent.com/144238665/332934618-7304f040-59db-4488-a2b1-cedc60cb841d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MTI3MTMsIm5iZiI6MTcxNjQxMjQxMywicGF0aCI6Ii8xNDQyMzg2NjUvMzMyOTM0NjE4LTczMDRmMDQwLTU5ZGItNDQ4OC1hMmIxLWNlZGM2MGNiODQxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMTEzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Njg2MzNhZDBlZjIwNTY0MWFmMWJmMzdjMWNmNmMwYzQxMzA2NTlkZGQ0YzI0NGJiZTM1MzhmYjUzNDljOGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AnT1yO6kw1jQWiAaVDgjPXPshpt8eQELaZoPt5TgI1I) the clones of .NET Host process eat all RAM (32 Gb) and CPU.
> > Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.9.7
> 
> This is strange, it actually helped me. Try manually adding it to the environment variables through this place: <img alt="image" width="455" src="https://private-user-images.githubusercontent.com/71682514/332962178-8c56b8f2-2498-4f61-a435-c60597a938ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjEwNDYsIm5iZiI6MTcxOTE2MDc0NiwicGF0aCI6Ii83MTY4MjUxNC8zMzI5NjIxNzgtOGM1NmI4ZjItMjQ5OC00ZjYxLWE0MzUtYzYwNTk3YTkzOGZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE2MzkwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ODYzZTQ2OGQ5ZDEyNDFlMThlNDY2Njk4YjY0ZDFlMThiZWJmMWU1NjI3NDhjZDc1MjE3M2IxN2NlZjIxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SI3kCc1CGg6ctB8NRJnlFO8htsll8vCVmITBSJG-uos">

I can confirm this workaround is effective, fixing this issue in VS 2022.

**Comment by kleineluka** [comment]
I'm not sure why this was marked as completed when this is very much still happening. The worst is that the processes don't exit with the IDE, just hanging around for no reason?

**Comment by oliverdrummond** [comment]
> I'm not sure why this was marked as completed when this is very much still happening. The worst is that the processes don't exit with the IDE, just hanging around for no reason?

Yes. I've been having exactly the same issue.

**Comment by xgreymx** [comment]
Still happening

**Comment by splitice** [comment]
Still an issue
