### ISSUE TITLE
[BUG] Omnishap commands failed

### ISSUE THREAD

**Issue by AndresGMD** [microsoft/vscode-dotnettools#582]
### Describe the Issue

Hi!!

Currently when I installed C# Dev kit the Omnisharp commands fail without this extension works fine.

If I excecute ctrl+shift+p Omnisharp: Select project I get:

![image](https://github.com/microsoft/vscode-dotnettools/assets/90065355/7de9ea68-24db-4ecd-97fb-51122a2f02b5)

If I excecute ctrl+shift+p Omnisharp: Restart Omnisharp I get:

![image](https://github.com/microsoft/vscode-dotnettools/assets/90065355/f947780f-a365-43bf-ac53-271d44d503a2)

etc..

### Steps To Reproduce

1. Execute command palette: crtl+shift+p
2. Execute (ge. Omnisharp: Restart Omnisharp)
3. Get the error.

### Environment Information

- OS: Microsoft Windows 11 Pro Version: 10.0.22621 N/A Build 22621
- VS Code Version 1.83.0
- **C#** v.2.5.30
- **C# Dev Kit**: v0.5.150
-
I have installed different versions of SDK's because I have projects with netcore 6.0 and 7.0. To run any project I create a global.json file in the root of each project.

```
> dotnet --list-sdks
6.0.413 [C:\Program Files\dotnet\sdk]
7.0.400 [C:\Program Files\dotnet\sdk]
```

**Comment by timheuer** [comment]
Correct, @AndresGMD this is by design.  Per the setting:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/40dd44ca-1459-474e-aec7-0b1e43806580)

and documentation: https://github.com/dotnet/vscode-csharp/blob/main/README.md#how-to-use-omnisharp

I think probably a better error message maybe we could provide here indicating that -- do you have suggestions that would have made it clearer for you? A simple "OmniSharp commands will not function if C# Dev Kit is enabled"?

**Comment by AndresGMD** [comment]
Thanks so much @timheuer I realized that it is not necessary to generate the assets for debugging with VScode so it is not necessary to have omnisharp server enabled.
