### ISSUE TITLE
[BUG] Caret position on mouse select

### ISSUE THREAD

**Issue by viniciusjarina** [microsoft/vscode-dotnettools#617]
### Describe the Issue

When using the mouse to position the cursor to a different line, VS Code should position the caret with the proper indentation, for instance if is inside a class it should be indented 2 spaces (namespace, class scope)
Here is how it works on on Visual Studio:

This is VSMac

https://github.com/microsoft/vscode-dotnettools/assets/926868/7dcd6382-2a30-477e-aed3-e1751cf36055

This is VSCode: (notice VS code don't indent the caret position you are forced to do the tab your self)

https://github.com/microsoft/vscode-dotnettools/assets/926868/a6657beb-a820-4dfe-9c6d-b9c3e57e3094

I really think .NET on VSCode have potential. But this kind of paper-cut make really annoy to use it. 

### Steps To Reproduce

Try to move the cursor clicking different lines

### Expected Behavior

It should just behave like VS or VSMac editor

### Environment Information

VSCode: Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (4 days ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.6.0

C# v2.6.24
C# Dev Kit v0.5.150

**Comment by dibarbet** [comment]
This works in VS because VS supports virtual space - so you can put the caret there but not actually insert any space into your document until you start typing.

VSCode does not currently support virtual space, issue requesting support is here -https://github.com/microsoft/vscode/issues/13960

Closing this issue as we're not planning to do anything here without platform support.

**Comment by viniciusjarina** [comment]
Hi @dibarbet thank you for the feedback. But I think you got a few things wrong.

That's **not** virtual space. Virtual Spaces on VS allow you to click anywhere and position the caret on that location.

If you try your VS editor with Virtual Spaces **disabled** you will see that VS still position the carets in the right location (indented).


An alternative solution would be to indent as soon the user start typing or maybe like JetBrains editor that fix the indentation when the user type the property/field/function

https://github.com/microsoft/vscode-dotnettools/assets/926868/aee231a4-aeef-40ea-b898-22df20f3fdc3

Would still be better than do nothing. I would keep this issue open and pending because that is the kind of paper cut that people complain when moving from VS to VSCode.

**Comment by dibarbet** [comment]
> That's not virtual space. Virtual Spaces on VS allow you to click anywhere and position the caret on that location.

@viniciusjarina In VS the feature that places the caret at the right indentation level does use virtual space, even if you uncheck the 'Enable virtual space' option.  You can verify this by turning on the 'View whitespace' setting which will show that there is no 'real' whitespace inserted until you start typing.  For example:
![indent_whitespace](https://github.com/microsoft/vscode-dotnettools/assets/5749229/b1028d29-8587-4963-b11e-ea42bc3f0fd9)

The 'Enable virtual space' option only controls if you can place the caret *anywhere* in the document.  We still use the platform support for virtual space for smart indentation, because having a caret move modify the document is a bad experience.

And I agree, the VS experience here is better.  But we can't do exactly that without virtual space.

> An alternative solution would be to indent as soon the user start typing or maybe like JetBrains editor that fix the indentation when the user type the property/field/function

So something like this should generally work in VSCode if you turn on 'Format on type' in vscode.  However there may be bugs here.  If you find cases where the format on type is not working as you would expect, please file a new bug here - https://github.com/dotnet/vscode-csharp/issues
<img width="647" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5749229/4cbed189-7e62-48fd-897b-f63384642c75">

![format_on_type](https://github.com/microsoft/vscode-dotnettools/assets/5749229/22c61f25-988d-421a-aa3d-1e3c68ee7608)

**Comment by m6502** [comment]
And this is what happens when not planing for a basic architectural feature. Virtual Space may be for you or not, but the capacity of using it is required for a ton of sugary features even if you don't enable it. In this case, an user is expecting smart indentation but it's not possible without the Virtual Space capability. 

The VSCode team sometimes seems like it must be comprised of young engineers who never used a proper code editor before. If they could see how slow VSCode is for some of us and how much of a drag to our productivity these issues can be when we are forced to use their editor, they would end up crying.
