### ISSUE TITLE
[SUGGESTION] Test Explorer run only failed Test

### ISSUE THREAD

**Issue by SchneiderMK** [microsoft/vscode-dotnettools#626]
### Describe the feature you'd like

I'd like to be able to run all failed test from a previous test run.

### Alternatives considered

Same feature could be archived if it is possible to run all test for an active filter e.g. filter "Show only Failed Tests" -> Run Test with Filter -> only failed test are executed.

**Comment by webreidi** [comment]
@SchneiderMK if you apply a filter and then click Run all tests, it will only run the tests displayed in the list. In the picture below I have filtered to failed tests and then clicked run all and it only ran my failed test.

![image](https://github.com/microsoft/vscode-dotnettools/assets/55603905/2f292c46-c240-4be5-8520-c1a001b9d944)

**Comment by SchneiderMK** [comment]
Yes, thats exactly what I'm looking for. Thank you. I've tried it with an older version an it did run all my test with an active filter. Now it does exactly what I'm wanted 👍

**Comment by SchneiderMK** [comment]
Yes, thats exactly what I'm looking for. Thank you. I've tried it with an older version an it did run all my test with an active filter. Now it does exactly what I'm wanted 👍

**Comment by cawoodm** [comment]
Every Test Framework I know has a "Run Failed Tests" option. 

To me filtering and clicking "Run All Tests" is a workaround - The button "Run All Tests" should run *all* tests, not "Run All Visible/Filtered Tests". 

The workaround is not intuitive since it's also not obvious to users that a @failed filter exists and how to use it. Unless everyone is supposed to read this workaround by googling this problem, a new button would make sense.

**Comment by webreidi** [comment]
Opened issue on VS Code, as the core functionality of the Test Explorer is implemented in VS Code. C# Dev Kit only enables C# to work within VS Code.

**Comment by webreidi** [comment]
@cawoodm just found out that, although there isn't a button, you can use "Test: Run failed tests" command from the command palette and it runs the failed tests only.
