### ISSUE TITLE
.Net: New project resulted in an error

### ISSUE THREAD

**Issue by Dru01** [microsoft/vscode-dotnettools#693]
Type: <b>Bug</b>

Install C# Dev Kit 1.1.5 or 1.0.14 version, with C# 2.9.20 and .Net install tool 2.0.0 extension version, try to run ".Net: New Project..." from command palette it will result in an error:

command 'csdevkit.addNewProject' not found.

Extension version: 1.1.5
VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:59.022Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (8.36GB free)|
|Process Argv|--crash-reporter-id 1b2400ad-5b4d-411e-9f4f-1d09e9e8be4f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30880072
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss2:30879913
pythonmypyd1:30879173
pythoncet00cf:30874137
pythontbext0:30879054
dsvsc016:30880769
dsvsc017cf:30880893
aa_t_chat:30882232

```

</details>

**Comment by smitpatel** [comment]
The error indicates that the command wasn't registered but calling .NET new project should activate the extension and register the command. Can you share a recording of the behavior? Also check output tab if there are logs for C# dev kit. If yes, can you share those?

**Comment by Dru01** [comment]
Sure, here it is


https://github.com/microsoft/vscode-dotnettools/assets/37126509/736f22fc-5ca4-41bc-8a32-7e0499356b3a

And the ouput was this:

2023-11-07 17:44:04.034 [warning] Via 'product.json#extensionEnabledApiProposals' extension 'ms-dotnettools.dotnet-interactive-vscode' wants API proposal 'languageConfigurationAutoClosingPairs' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
2023-11-07 17:44:04.417 [warning] [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
2023-11-07 17:44:04.781 [warning] No search provider registered for scheme: file, waiting
2023-11-07 17:44:07.090 [info] [perf] Render performance baseline is 18ms
2023-11-07 17:44:07.528 [error] Activating extension 'GitHub.vscode-pull-request-github' failed: Cannot find module 'c:\Users\batma\.vscode\extensions\github.vscode-pull-request-github-0.76.0\dist\extension'
Require stack:
- c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- .: Error: Cannot find module 'c:\Users\batma\.vscode\extensions\github.vscode-pull-request-github-0.76.0\dist\extension'
Require stack:
- c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1129:15)
    at Function.s._resolveFilename (node:electron/js2c/utility_init:2:2786)
    at Module._load (node:internal/modules/cjs/loader:974:27)
    at Function.f._load (node:electron/js2c/asar_bundle:2:13377)
    at Function.r._load (c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:153:5647)
    at Function.c._load (c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:29431)
    at Function.t._load (c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:35262)
    at Module.require (node:internal/modules/cjs/loader:1195:19)
    at Module.patchedRequire [as require] (c:\Users\batma\.vscode\extensions\github.copilot-1.134.0\node_modules\diagnostic-channel\dist\src\patchRequire.js:16:46)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Function.i [as __$__nodeRequire] (c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\loader.js:5:98)
    at h.vb (c:\Users\batma\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:30610)
    at async Promise.all (index 0)

**Comment by smitpatel** [comment]
@Dru01 - Thanks for sharing video. Looks like extension didn't register command at all as if extension is not installed. Can you check if extension is present in vscode installation? If yes, can you open an existing project or solution in vscode. I will check why vscode wouldn't get commands from installed extension like that. Thanks.

**Comment by Dru01** [comment]
@smitpatel - No problem.

By vscode installation you mean this?

![image](https://github.com/microsoft/vscode-dotnettools/assets/37126509/953ef033-6aa5-4b28-80cd-28dd84416021)

**Comment by Dru01** [comment]
@smitpatel Don't know what was happening but I had to do a fresh install of my windows and now it works like a charm.

**Comment by smitpatel** [comment]
@Dru01 - That's great. I suspect while the extension was installed in vscode, it was in broken state somehow, so it didn't pick up global command you saw error that command not found. I am not sure if we can trace the root cause of it now. I will close the ticket but if you see it again through normal usage that is certainly something we want to investigate.

If anyone sees the same issue, try uninstalling the C# dev kit extension and install it again. Most likely that should fix the issue.

**Comment by hs1955** [comment]
Hi, I have encountered the same problem on Kubuntu, and snap store VSCode.

I've tried re-installling the dev kit, but that didn't work.
Then I tried re-installing vscode, but that didn't fix it either.
Then I tried deleting all my extensions, then re-installing VSCode, restarting my laptop, but none of this solved my issue.

I also did a fresh re-install of dotnet beforehand from the Ubuntu repositories rather than the latest Microsoft ones, but I'm sure it should be sufficient. I did that to make sure dotnet was only using packages from one source.

Anyways I'm quite stumped at how is this even possible haha. This all started when I wasn't able to stop at breakpoints with C# Godot. I was able to run Then I worked all the way back, and it seems that my C# extension is broken.

![image](https://github.com/microsoft/vscode-dotnettools/assets/92299208/3f7469a8-f214-407d-accb-36cb68f50710)

---
Here's my VSCode details:
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.8.0-31-generic snap

---
And OS information:
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i5-8365U CPU @ 1.60GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: HP
Product Name: HP ProBook 640 G5
