### ISSUE TITLE
[BUG] Run project with associated file has lots of unexpected output

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#705]
### Describe the Issue

When clicking "Run project associated with this file", I get a lot of stuff that clouds the terminal making it time consuming to parse for the output. It also appear to display the unwanted text twice. Since this is the simple use case I am using for the beginner tutorial on the .net website it would be great if the output was cleaner for new learners/beginners. For now I've had to leave out a screenshot of the output but would love to add one once it's cleaner

![image](https://github.com/microsoft/vscode-dotnettools/assets/19276747/3c0a0a41-57a3-48f6-8184-8e7af5d31a03)

### Steps To Reproduce

1. Create simple console app 
2. Have it print anything

### Expected Behavior

Would not expect to see any of the blue code in the terminal and just have something like below to keep it really clean

**PS C:\Users\clregio\OneDrive - Microsoft\Dev\MyConsoleApp> 
Hello, World!**

### Environment Information

VS Code: 1.84.2 
C# Dev Kit: v1.0.14
C#: v2.10.28

**Comment by WardenGnaw** [comment]
The debugger provides this command to VS Code to launch the debugger.

If you wish to hide the command being executed, there is an open issue at VS Code https://github.com/microsoft/vscode/issues/100522

One potential workaround is to use the debug console instead of the terminal so you do not see the debugger command in the terminal window.
