### ISSUE TITLE
[BUG] Improve readme content for readability

### ISSUE THREAD

**Issue by abergquist** [microsoft/vscode-dotnettools#761]
### Describe the Issue

I recommend the following at https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit:

1. Since "Roslyn powered" is a compound modifier (cf. https://en.wikipedia.org/wiki/Compound_modifier), I recommend replacing it with "Roslyn-powered" in the following bullet points:

- Roslyn powered language service for best in-class C# language features such as code navigation, refactoring, semantic awareness, and more

- Roslyn powered semantic awareness

2. With respect to the following bullet point:

- AI-Assisted development

and the following sentence:

You can also [uninstall](https://code.visualstudio.com/docs/editor/extension-marketplace#_uninstall-an-extension) it at the expense of some features if you're using a different AI-Assisted development extension.

it's good that you're already hyphenating "AI" and "Assisted"; I recommend, though, replacing "Assisted" with "assisted". That will make them consistent with the casing in the following sentence that appears later:

Auto-installing as part of C# Dev Kit, the [IntelliCode for C# Dev Kit](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.vscodeintellicode-csharp) extension enhances the AI-assisted support beyond the basic [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense) code-completion found in the existing C# extension.

3. I recommend inserting a comma immediately after "Kit" in the following sentence:

With C# Dev Kit your tests in XUnit, NUnit, MSTest and bUnit will be discovered and organized for you more easily for fast execution and results navigation.

**Comment by GregSweats** [comment]
__@webreidi is there code with an updated `README.md` in it that's ready to merge or has been merged?__

If there is nothing yet, I'd be happy to take a stab at it. Anything I can do to get involved because your GitHub workflow looks amazing, at least in the ~5 minutes I spent looking at 😉

You can see an example of how I wrote a long README for my first open-source published repo. It went nowhere and I didn't win, so I just leave it there in case someone weirdly wants it. 
I have not read this for a year or two, commit history should be accurate.

🦖 The `trxn8r (Transactionator)` project went a bit on the avant garde, artistic side of things, but don't worry, I know how to tone things down.

The Issue Description is plenty to start with (great work OP).

You know, it's amazing, I accidentally stumbled here looking for a completely different extension. I am SO VERY HAPPY to have found an open-source project with such AMAZING, yet SIMPLE, monthly Iteration Plans. 👏👏👏 Look forward to a future here. Apologies in advanced while I get used to the workflow, and GitHub, as I use GitLab during the day.

🙏 Thank you!

Warning...I am notoriously awful at checking notifications and remembering to follow-up, but I will keep a note to check here.

**Comment by abergquist** [comment]
Hi, I see that the "grammatical opportunities" I reported have been fixed at https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit.

I noticed, though, that when I go to **Extensions** from **VS Code** and check out **C# Dev Kit** there, that they are still extant issues. Does the [fixed (release pending)](https://github.com/microsoft/vscode-dotnettools/labels/fixed%20%28release%20pending%29) label above mean that they will be released there at some point as well?

**Comment by webreidi** [comment]
@abergquist Yes, this was fixed in the latest pre-release version of C# Dev Kit and will make it into our next stable version soon.

**Comment by abergquist** [comment]
Thanks, @webreidi !
