### ISSUE TITLE
[BUG] Run without debugging does not launches browser for `Blazor` & `ASP.NET Web API`

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#788]
I'm reopening [issue](https://github.com/microsoft/vscode-dotnettools/issues/259) because it is not fixed. `Run without debugging` hot key (`ctrl+F5`) or quick button on bar does not launches browser. Tested `Web Api` And `Blazor` projects.

Browser does not launches  If my settings are:

`"csharp.debug.console": "externalTerminal",`

but if my settins are:

`"csharp.debug.console": "integratedTerminal",`

browser launches. 

I'm on `Windows 11`.

https://github.com/microsoft/vscode-dotnettools/assets/38082501/7da470f1-7cb1-4172-b2a2-52ec674f5505

**Comment by WardenGnaw** [comment]
Can you share which version of the C# Extension and C# Dev Kit you are using?

**Comment by BachiMjavanadze** [comment]
> Can you share which version of the C# Extension and C# Dev Kit you are using?

The video is old, I'm lazy to make a new one. Using the latest Programs/Extensions/OS:

```
C# Dev Kit, v1.2.2
C#, v2.13.10
Windows 11 Home, 22H2
```

**Comment by WardenGnaw** [comment]
I think we found the issue.

For projects that spin up a browser, its required that the console type to be `internalConsole`. We have a bug that switches the web projects to use the user settings instead of using `internalConsole` as the tooling that requires starting a web browser requires `internalConsole`.

See https://code.visualstudio.com/docs/csharp/debugger-settings#_starting-a-web-browser

**Comment by BachiMjavanadze** [comment]
please fix it

**Comment by WardenGnaw** [comment]
This should have been fixed in the January release
