### ISSUE TITLE
Add New Project: Utilize files.dialog.defaultPath when showing dialogue box

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#83]
Please create start window and add following features:

- choose target framework.
- place a solution and a project in the same directory or separately.
- give different names to solution and project.
- choose default folder location into settings and ability to change it during the project creation.

![Untitled](https://github.com/microsoft/vscode-dotnettools/assets/38082501/0f1c80bf-a0f9-4321-a1b3-fdbf1082189a)

**Comment by smitpatel** [comment]
We are planning to add UI which would allow user to select options specified above but UI won't be the same.

**Comment by smitpatel** [comment]
@sayedihashimi - Our current design allows for choosing tfm and location for project. We don't have prompt for placing solution and project in same directory or ability to give different name to solution. Let's discuss what we plan to do for those.

**Comment by sayedihashimi** [comment]
For the solution name, I see how that can be valuable, but it's also easy to change after the fact. @webreidi have we received any other feedback on being able to customize the solution name during creation?

I think we should avoid "place solution and project in same folder", it causes lots of issues because .NET Core supports globbing. One example is Aspire, it doesn't work when you select that option. I think we should not enable that option in C# Dev Kit. That option pre-dated .NET core in Visual Studio. If Visual Studio was strictly a .NET IDE I don't think you'd see that option there.

**Comment by sayedihashimi** [comment]
Thanks @webreidi, sounds like a good plan.

**Comment by smitpatel** [comment]
Addressing user asks in this issue
- Ability to choose tfm is available in latest release version of C# dev kit.
- Based on discussion above, we are not planning to add option to put solution and project in same directory.
- #1127 tracks ability to provide solution name when creating new project without existing solution. #1132 tracks ability to rename solution file from solution explorer.

@BachiMjavanadze - Can you elaborate on the last ask? Currently new project will open dialogue box with last opened folder. Which is same behavior as VS Code when you do open folder.

**Comment by BachiMjavanadze** [comment]
>  Currently new project will open dialogue box with last opened folder.

In my case (latest  `Windows 11 Pro` and `VSCode`), the new project always opens `C:\Users\mjava\`. It does not suit me, so I use the setting to determine the desired location: `"files.dialog.defaultPath": "F:\\Development"`.

>  Can you elaborate on the last ask?

you have already described the last ask. This is how my `Visual Studio IDE 2022` works but not `VSCode`.

To be more precise: when I open the dialog window (to create new project) I should see the path of the previous project's parennt folder. Of course, this only applies when I'm creating a new solution with new project, not when I'm creating a new project within an existing solution.

**Comment by smitpatel** [comment]
@sayedihashimi @webreidi - Thoughts on user ask in last comment.

**Comment by webreidi** [comment]
@smitpatel, Sayed and I were talking about wanting to be able to "remember" user preferences and such when it came to things like this, but weren't sure what options we had cross workspace for VS Code besides the "settings" and not sure if default project location is something we should put in settings. I'd love to hear @sayedihashimi 's thoughts.

**Comment by sayedihashimi** [comment]
@BachiMjavanadze is `files.dialog.defaultPath` an existing setting in VS Code or something that you are proposing for this specific scenario?

**Comment by BachiMjavanadze** [comment]
> @BachiMjavanadze is `files.dialog.defaultPath` an existing setting in VS Code or something that you are proposing for this specific scenario?

Yes, it is existing setting in VS Code. Just copy-paste it in your settings.json and you will see

**Comment by sayedihashimi** [comment]
Thanks @BachiMjavanadze for the additional info. 

I think it would be nice to have a setting to control the default location of the project when there is no workspace loaded. From your comment it sounds like `files.dialog.defaultPath` is an existing setting that is used for new files. 

The only question I have is should we respect this setting or create a new named setting. If we were to start with respecting this setting, we can always add a new named setting specific to C# Dev Kit and then fall back to this setting. 

Since I’m not a VS Code expert, I’d like the opinions of some others before we make a conclusion. Maybe @DustinCampbell @DamianEdwards @baronfel @timheuer

**Comment by baronfel** [comment]
I didn't know about `files.dialog.defaultPath` before, but it does seem tailor-made for this scenario. I agree strongly with this sentiment:

> If we were to start with respecting this setting, we can always add a new named setting specific to C# Dev Kit and then fall back to this setting.

Leaning into platform-provided affordances and only deviating when necessary seems like a win!

**Comment by webreidi** [comment]
I love that there is a setting for this already! I agree with above.

**Comment by sayedihashimi** [comment]
Thanks for the feedback. It sounds like it would be good for us to support this setting. 

@smitpatel @webreidi

**Comment by smitpatel** [comment]
We don't specify default URI for folder to open when showing dialogue box during add new project. That means it uses whatever vscode think is most appropriate. I checked behavior in latest version of C# dev kit.
When open dialogue box is shown for workspace location when no workspace is open, vscode will use files.dialog.defaultPath if set else the home folder for the user.
When open dialogue box is shown for additional project when workspace is open (if user decides to change directory), then vscode show the most recent used directory in workspace.

Closing this as fixed as we don't need any additional work to support the setting.
