### ISSUE TITLE
[BUG] Cannot attach Debbuger

### ISSUE THREAD

**Issue by orlando320** [microsoft/vscode-dotnettools#875]
### Describe the Issue

the only way I can attached the debugger is if I completely close vscode and unity then open them both back up but then when I do unity freezes until I release it from the debugger. When it doesn't connect I get this error "Failed to attach debugger to 127.0.0.1:56200

### Expected Behavior

- Closed VS and in Unity > Edit > Preferences > External Tools and Click on "Regenerate project files" (you don't need to check anything else, just click the button)
- Closed both VS code unity (this fixes the attachment issue but not when it locks up unity)
- 

### Environment Information

I am running unity 2022.3.1 on Windows 11 in VSCODE (ver 1.85.2)

**Comment by jbevain** [comment]
@orlando320, so attaching the debugger works once, but subsequent tentatives fail to attach unless you restart Unity?

Could you modify your `.vscode/launch.json` file to enable some logging:

```
    "configurations": [
        {
            "name": "Attach to Unity",
            "type": "vstuc",
            "request": "attach",
            "logFile": "${workspaceRoot}/debug.log"
        }
```

And send the resulting log file to vstusp@microsoft.com? Thank you!

**Comment by desplesda** [comment]
I'm also seeing an error very similar to this, where the debugger fails to attach. 

When I attempt to connect the debugger, VS Code appears to start a debug session, and shows the debug controls (the floating continue/step/disconnect pane). The Debug Console appears, but no text appears in it. Unity's 'Debug Mode' icon turns blue, indicating that it believes a debugger is attached. When I click the Disconnect button, the debug session ends in VS Code, and Unity's 'Debug Mode' icon turns yellow, indicating that the debugger has disconnected.

My only difference from @orlando320 is that Unity is not locking up - it continues to operate normally, as though the debugger had successfully attached.

My steps:
- Launch my Unity project
- Regenerate project files, just to be sure.
- Set Unity to Debug Mode, to allow debugger attaching.
- Launch VS Code.
- Start a debugger session using the Attach to Unity configuration.

I've sent a copy of my debug log to vstusp@microsoft.com.

My environment:
- macOS 12.6.2
- Unity: 2021.3.9f1
- Unity for Visual Studio Code: 0.9.4
- C# for Visual Studio Code: 2.15.30
- C# Dev Kit: 1.2.7

I've also tested this with the previous version of the VS Code extensions, with the exact same steps results:
- Unity for Visual Studio Code: 0.9.3
- C# for Visual Studio Code: 2.14.8
- C# Dev Kit: 1.1.16

**Comment by jbevain** [comment]
Closing this as we haven't heard in 3 weeks. Feel free to reopen or send the logs as requested for further investigation. Thanks!

**Comment by AntonioDrk** [comment]
Hello,
I don't know how relevant it is, but it somewhat is happening to me today as well, I've managed to get the debug.log out.
Hope it helps:

> --> R (attach-2): {"type":"response","request_seq":2,"success":false,"command":"attach","message":"Failed to attach debugger to 127.0.0.1:56160","body":{},"seq":2}
<--   C (disconnect-3): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3}
Stopping due to fatal error: NullReferenceException: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SyntaxTree.VisualStudio.Unity.Debugger.UnityEngine.Detach()
   at Microsoft.VisualStudio.Unity.AD7DebugAdapter.HandleDisconnectRequest(DisconnectArguments arguments)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.HandleProtocolRequest(String requestType, Object requestArgs)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.OnProtocolRequestReceived(Object sender, RequestReceivedEventArgs e)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.OnRequestReceived(String command, IRequestResponder responder)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.HandleDisconnectRequestAsync(IRequestResponder`1 responder)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.DebugAdapterBase.<InitializeProtocolClient>b__5_12(IRequestResponder`1 r)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.RequestInfo`1.Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.IRequestInfo.InvokeHandler(DebugProtocol protocol, ProtocolRequest request, Object args)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingRequest(String msg)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingMessage(String msg)
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ProcessMessageBody()
   at Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc()

**Comment by RobTranquillo** [comment]
I have the same problem with my everyday project that I have been working on for over a year. Since some of the latest versions of VSCode, the debugger stops connecting at some point. Only a restart of VSCode and Unity fixes the problem. Until it reappears. 

I actually see the problem every day. But even after a few experiments, I have not yet been able to reproduce it for sure. My guess is that it could be caused by a complex mix of OpenVPN, Tailscale, multiple Unity editors and VSCode editors connected for debugging in conjunction with Windows sleep mode (Supend-To-Disk)

Output when it fails:
```
--> R (attach-2): {"type":"response","request_seq":2,"success":false,"command":"attach","message":"Failed to attach debugger to 127.0.0.1:56636","body":{},"seq":2}
<--   C (disconnect-3): {"command":"disconnect","arguments":{"restart":false},"type":"request","seq":3}
--> R (disconnect-3): {"type":"response","request_seq":3,"success":true,"command":"disconnect","body":{},"seq":3}
```

**Comment by Entretoize** [comment]
For the even restarting both VSCode and Unity does nothing, Unity is locked if I start debugging !

**Comment by wuxingogo** [comment]
Versions:

Unity 2023.3.22f1
Unity Visual Studio package: 2.0.22
VS Code: v1.95.3
VS Code Unity Extension: 1.0.4

**Comment by vlab22** [comment]
Unity 2022.3.32f1
Unity Visual Studio Editor package:  2.0.23
VS Code: v1.103.1
VS Code Unity Extension: 1.1.2 (visualstudiotoolsforunity)
