### ISSUE TITLE
[BUG] Dev kit not working when there is root solution with multiple projects

### ISSUE THREAD

**Issue by TharinduBalasooriya** [microsoft/vscode-dotnettools#888]
### Describe the Issue

If the project structure is as follow , C# dev kit extension will not be activated properly , projects under the solution is not listed
![image](https://github.com/microsoft/vscode-dotnettools/assets/53065333/c0b7bec7-fbb2-42fe-8fa0-7bf0f9c18062)
![image](https://github.com/microsoft/vscode-dotnettools/assets/53065333/c60b8504-1c5d-4bc8-a1ad-2ff90ecee61b)

Visual Studio view : 
![image](https://github.com/microsoft/vscode-dotnettools/assets/53065333/3472888c-6086-4061-82b3-c8b84133e28d)

### Steps To Reproduce

1 . Create empty solution 
2. Add multiple projects to empty solution
3. Try to open the root project

### Expected Behavior

Dev Kit should be able to show the projects under the root solution

**Comment by timheuer** [comment]
@TharinduBalasooriya Can you reload the window (from the command palette choose "Reload Window") and does it find them?  And stating the obvious here since you said it, but confirming that the SLN file actually does include reference to the 2 projects?

Also, the following would be helpful:
- Type of projects (what .NET target)
- Any output from the "C# Dev Kit" output window logs
