### ISSUE TITLE
[BUG] Unit Test Debugging very slow in GitHub Codespaces (Linux)

### ISSUE THREAD

**Issue by asilverman** [microsoft/vscode-dotnettools#895]
### Describe the Issue

When I debug my C# code in Github Codespaces, it takes minutes before the debugger is initialized and the first breakpoint is hit. Also stepping through code takes 5-10s per code line. When I do this on my local VS Code installation, it is fast (within a second). 

### Steps To Reproduce

1. Create a codespaces variant of your choice (see below for my choice) for the public repository azure/bicep
![Screenshot 2024-02-02 101058](https://github.com/microsoft/vscode-dotnettools/assets/9611108/a48ebb88-ae72-4101-b618-c22ffb3b6a46)1. Start a debug session on one of the tests from VSCode and step through the code. Any test will do.

[Link to video - Visible to MS Account Only](https://microsoft-my.sharepoint.com/:v:/p/asilverman/EezVq_SDX05Go0K4fJYuA70Bm8enTzA0F7HaObD6oLFfow?e=8jlcJ4&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D)
### Expected Behavior

I would expect the debugging performance to be reasonable and reactive for humans

### Environment Information

- Dev Containers 0.339.0 
- VS Code 1.87.0-insider (442c133fe92b5e2606c8242caae4e68938faccc7)
- C# Dev Kit: 1.3.8

**Comment by asilverman** [comment]
Uploading debug logs for codespaces (debug_logs_codespaces) and for localhost (debug_logs_localhost) to show the difference in the debugging experience.
[debug_logs.zip](https://github.com/microsoft/vscode-dotnettools/files/14215352/debug_logs.zip)

**Comment by WardenGnaw** [comment]
After some investigation, there are a couple things causing a slowness during the debug session.

If you are debugging though a unit test, the test system starts the debugger via an attach request.
Because its debugging via attach, this forces the runtime to use non-kernel read memory APIs which are much slower. 
Which are causing any reads to the target process memory to be slower than if it used kernel APIs. 

Workarounds:
- Set `/proc/sys/kernel/yama/ptrace_scope` to `0` as this will allow the Runtime to use Kernel APIs (Not sure if Codespaces lets you modify this file.
- [Requires changes in C# Dev Kit] Test starts the debugger via a `launch` instead of `attach`. If launched, then the debugger can be the parent process of the target process.

**Comment by asilverman** [comment]
@WardenGnaw thank you for looking into this, would setting `"runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ]` [see docs](https://containers.dev/implementors/json_reference/) be equivalent to configuration of the yama ptrace scope?

**Comment by ocallesp** [comment]
@ocallesp  needs to transfer this issue to the debugging team

**Comment by peterwald** [comment]
This is currently by design. It could possibly be improved by enhancement #1048, however there are other reasons we decided to use attach rather than debugger launch.
