### ISSUE TITLE
[BUG] Debugger Source Lookup

### ISSUE THREAD

**Issue by markusroessler** [microsoft/vscode-dotnettools#933]
### Describe the Issue

Please document, where the Debugger tries to find Source-Files and how to configure this. I'm trying to step into MAUI code. Symbols are loaded (can see Line-Numbers in "Call Stack"-View) - but Sourcefiles are not - Message: "Could not load source 'Button.cs': No source available."
![Screenshot 2024-02-20 at 00 22 54](https://github.com/microsoft/vscode-dotnettools/assets/32437037/ba5e4506-e187-42df-9b2a-9281c4dedf12)

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1999777">1999777</a>

**Comment by mauroa** [comment]
Hi @markusroessler, this issue has already been fixed in latest .NET MAUI pre-release. We've introduced a new feature to use the .NET Core Debugger Backend (vsdbg) for debugging, which introduces a lot of improvements, fixes and new features as well. You can use the C# debugger settings, configure how to handle exceptions, and also inspect source code.
In order to make usage of this feature, the only requirement is to use .NET 8.0.200 or higher (in fact what we really require is the .NET runtime 8.0.3, which is included from the 8.0.200 SDK). In case you don't meet those requirements, the old debugger implementation will be used by default.
Please give it a try and let me know if you have any doubts. You can verify the usage of the new debugger in the Debug Console and also on the .NET MAUI output, where it should indicate a "UseVSDbg" value after launching your app for debugging.

**Comment by markusroessler** [comment]
@mauroa I will give it a try. Thank you!
