### ISSUE TITLE
Project path contains special characters, which can be an issue when opening Visual Studio UnityEngine.Debug:LogWarning (object)

### ISSUE THREAD

**Issue by AounHaider133** [microsoft/vscode-dotnettools#949]
### Describe the Issue

I am trying to integrate vscode with unity. I have followed the instructions provided in the vscode extension. step 1 was to enable/unlock vscode version 2.0.22. When i tried to click on "Regenerate project files" in external tools of preferences in unity, i encountered a warning related to path. How to resolve this issue? Kindly help!

### Steps To Reproduce

![Screenshot 2024-02-25 120834](https://github.com/microsoft/vscode-dotnettools/assets/124600838/70c64766-45b6-4aad-908e-d07d87a354dd)

### Expected Behavior

Successfull integration of vscode with unity

### Environment Information

Windows Operating System
VsCode extension "Unity"
Unity 2022.3.20f1

**Comment by jbevain** [comment]
Hi,

I think there are two different things.

In the screenshot you added, the External Tools editor clearly show “Visual Studio 17.9” instead of Visual Studio Code. You need to select Visual Studio Code if you want to use the Visual Studio Code integration.

Then there's the warning. There's a character in your project name that could be problematic because Unity generates a solution file according to the name of your folder. So if your path contains a character in `['?', '&', '*', '"', '|', '<', ';', '#', '%', '^']`, you could encounter issues and we recommend using a path without special characters.

**Comment by jbevain** [comment]
I'm going to close this as we haven't heard back. Feel free to re-open if you're still encountering issues. Thank you!
