### ISSUE TITLE
[SUGGESTION] Disable telemetry

### ISSUE THREAD

**Issue by Newex** [microsoft/vscode-dotnettools#985]
### Describe the feature you'd like

I would like to opt out of telemetry.

### Alternatives considered

Preferably make the telemetry OPT-IN instead of OPT-OUT.  
Do not use dark patterns, be ethical.

### Environment Information

multiple weird `values.xml` files. That keeps reappearing even when deleted.

**Comment by jonathanjyi** [comment]
Hi @Newex, the C# Dev Kit extension respects the telemetry privacty settings set in VS Code . if you disable VS Code telemetry then the extension will not send telemetry. You can find more information here: [Disable Telemetry Reporting](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting).

**Comment by sliekens** [comment]
@jonathanjyi is it possible to change Dev Kit to store these XMLs in the system temp folder? So we don't all have to update our .gitignore file. Thanks.

**Comment by jonathanjyi** [comment]
Hi @sliekens, yes we are looking into ways to make this a better experience. Can't give a time table yet, but it is being investigated.

**Comment by jonathanjyi** [comment]
Update here, we've discovered the issue and are working on a fix.

**Comment by jonathanjyi** [comment]
Fix is pending release. Multiple components needed to be updated regarding the .mono folder. 

Just a reminder that the sending of telemetry is controlled by the VS Code Telemetry Privacy setting which you can find more info for here: [Disable Telemetry Reporting](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting).

Internal files such as the values.xml will still be there (in the correct locations now) because they're used by C# Dev Kit for internal services.

**Comment by jonathanjyi** [comment]
This has been fixed in the following components and versions:
C# 2.31.19
C# Dev Kit 1.6.8
Intellicode 2.1.11

I would like to reiterate that if you follow [Disable Telemetry Reporting](https://code.visualstudio.com/docs/getstarted/telemetry#_disable-telemetry-reporting), then telemetry will not be sent from your machine. However, files such as values.xml will still be created for internal processes.
